// Auto-generated by scripts/sync-vinfast-catalog.mjs — do not edit manually
// Source: https://vinfastauto.com/vn_vi
// Last synced: 2026-06-23T10:01:37.907Z

export type VinFastHomeSpec = {
  value: string;
  label: string;
  highlight?: boolean;
  seats?: boolean;
};

export type VinFastHomeSlide = {
  title: string;
  subtitle?: string;
  image: string;
  imageAlt: string;
  imageClass: string;
  specs: VinFastHomeSpec[];
  primaryCta: string;
  secondaryCta: string;
  href?: string;
  detailHref?: string;
};

export type VinFastHeroBanner = {
  image: string;
  alt: string;
  href: string;
};

export const VINFAST_HERO_BANNERS: VinFastHeroBanner[] = [
  {
    image: "/images/vinfast/banners/hero-1.jpg",
    alt: "VinFast VF MPV 7 - Gia đình sum vầy hành trình trọn vẹn, tổng ưu đãi lên tới 124 triệu đồng",
    href: "https://shop.vinfastauto.com/vn_vi/dat-coc-o-to-dien-vinfast.html?modelId=Products-Car-VFMPV7",
  },
  {
    image: "/images/vinfast/banners/hero-2.jpg",
    alt: "VinFast chính thức xuất xưởng 1 triệu xe máy điện - Mãnh liệt chuyển đổi xanh 12/06/2026",
    href: "https://vinfastauto.com/vn_vi/vinfast-xuat-xuong-chiec-xe-may-dien-thu-1-trieu",
  },
  {
    image: "/images/vinfast/banners/hero-3.jpg",
    alt: "VinFast xe máy điện - Phố thêm xanh lướt hè phơi phới, tổng ưu đãi lên đến 16%",
    href: "https://shop.vinfastauto.com/vn_vi/dat-coc-o-to-dien-vinfast.html",
  },
  {
    image: "/images/vinfast/banners/hero-4.jpg",
    alt: "VinFast xe máy điện - Phố thêm xanh lướt hè phơi phới, tổng ưu đãi lên đến 16%",
    href: "https://shop.vinfastauto.com/vn_vi/dat-mua-xe-may-dien-vinfast",
  },
  {
    image: "/images/vinfast/banners/hero-5.jpg",
    alt: "VinFast Vinfascination đón hè rực rỡ - Ưu đãi giá bán lên đến 3%, tặng voucher Vinpearl",
    href: "https://shop.vinfastauto.com/vn_vi/dat-coc-o-to-dien-vinfast.html",
  },
  {
    image: "/images/vinfast/banners/hero-6.jpg",
    alt: "VinFast VF 3 Vinfascination mùa hè rực rỡ - Tặng voucher Vinpearl hoặc ưu đãi 2% giá bán",
    href: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf3.html",
  },
];

export const VINFAST_FEATURED_CARS: VinFastHomeSlide[] = [
  {
    title: "VF 9",
    subtitle: "E-SUV",
    image: "/images/vinfast/cars/vf9.webp",
    imageAlt: "VF 9",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "6-7",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "626 km",
        label: "Quãng đường lên tới",
      },
      {
        value: "1.274.150.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/vf9",
    detailHref: "https://shop.vinfastauto.com/vn_vi/car-vf9.html",
  },
  {
    title: "VF 8 All New",
    subtitle: "D-SUV",
    image: "/images/vinfast/cars/vf8-all-new.png",
    imageAlt: "VF 8 All New",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "5",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "480-500 km",
        label: "Quãng đường lên tới",
      },
      {
        value: "849.150.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/vf8-all-new",
    detailHref: "https://vinfastauto.com/vn_vi/dat-coc-xe-vf8-the-all-new-2026",
  },
  {
    title: "VF MPV 7",
    subtitle: "MPV",
    image: "/images/vinfast/cars/vf-mpv7.webp",
    imageAlt: "VF MPV 7",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "7",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "450 km (NEDC)",
        label: "Quãng đường lên tới",
      },
      {
        value: "728.910.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/vf-mpv7",
    detailHref: "https://vinfastauto.com/vn_vi/dat-coc-xe-vf-mpv7",
  },
  {
    title: "EC VAN",
    subtitle: "VAN",
    image: "/images/vinfast/cars/ec-van.webp",
    imageAlt: "EC VAN",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "2",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "150 km",
        label: "Quãng đường lên tới",
      },
      {
        value: "253.650.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/ec-van",
    detailHref: "https://shop.vinfastauto.com/vn_vi/vinfast-ecvan.html",
  },
  {
    title: "Minio Green",
    subtitle: "MiniCar",
    image: "/images/vinfast/cars/minio-green.webp",
    imageAlt: "Minio Green",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "4",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "170 km (NEDC)",
        label: "Quãng đường lên tới",
      },
      {
        value: "239.410.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/minio-green",
    detailHref: "https://shop.vinfastauto.com/vn_vi/minio-green.html",
  },
  {
    title: "Herio Green",
    subtitle: "A-SUV",
    image: "/images/vinfast/cars/herio-green.png",
    imageAlt: "Herio Green",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "5",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "326 km (NEDC)",
        label: "Quãng đường lên tới",
      },
      {
        value: "426.310.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/herio-green",
    detailHref: "https://shop.vinfastauto.com/vn_vi/herio-green.html",
  },
  {
    title: "Nerio Green",
    subtitle: "B-SUV",
    image: "/images/vinfast/cars/nerio-green.webp",
    imageAlt: "Nerio Green",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "5",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "318,6 km (NEDC)",
        label: "Quãng đường lên tới",
      },
      {
        value: "668.000.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/nerio-green",
    detailHref: "https://shop.vinfastauto.com/vn_vi/nerio-green.html",
  },
  {
    title: "Limo Green",
    subtitle: "MPV",
    image: "/images/vinfast/cars/limo-green.png",
    imageAlt: "Limo Green",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "7",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "450 km (NEDC)",
        label: "Quãng đường lên tới",
      },
      {
        value: "666.610.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/limo-green",
    detailHref: "https://shop.vinfastauto.com/vn_vi/limo-green.html",
  },
  {
    title: "VF 3",
    subtitle: "MiniCar",
    image: "/images/vinfast/cars/vf3.webp",
    imageAlt: "VF 3",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "4",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "210 km (NEDC)",
        label: "Quãng đường lên tới",
      },
      {
        value: "268.780.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/vf3",
    detailHref: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf3.html",
  },
  {
    title: "VF 5",
    subtitle: "A-SUV",
    image: "/images/vinfast/cars/vf5.webp",
    imageAlt: "VF 5",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "5",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "326,4 km (NEDC)",
        label: "Quãng đường lên tới",
      },
      {
        value: "470.810.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/vf5",
    detailHref: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf5.html",
  },
  {
    title: "VF 6",
    subtitle: "B-SUV",
    image: "/images/vinfast/cars/vf6.webp",
    imageAlt: "VF 6",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "5",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "480 km (NEDC)",
        label: "Quãng đường lên tới",
      },
      {
        value: "613.210.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/vf6",
    detailHref: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf6.html",
  },
  {
    title: "VF 7",
    subtitle: "C-SUV",
    image: "/images/vinfast/cars/vf7.webp",
    imageAlt: "VF 7",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "5",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "496 km",
        label: "Quãng đường lên tới",
      },
      {
        value: "702.210.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/vf7",
    detailHref: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf7.html",
  },
  {
    title: "VF 8",
    subtitle: "D-SUV",
    image: "/images/vinfast/cars/vf8.webp",
    imageAlt: "VF 8",
    imageClass: "h-full w-full object-contain object-left",
    specs: [
      {
        value: "5",
        label: "chỗ ngồi",
        seats: true,
      },
      {
        value: "471 km",
        label: "Quãng đường lên tới",
      },
      {
        value: "866.150.000 VNĐ*",
        label: "Giá bán từ",
        highlight: true,
      },
    ],
    primaryCta: "KHÁM PHÁ NGAY",
    secondaryCta: "ĐẶT LỊCH LÁI THỬ",
    href: "/oto/vf8",
    detailHref: "https://shop.vinfastauto.com/vn_vi/car-vf8.html",
  },
];

export const VINFAST_FEATURED_SCOOTERS: VinFastHomeSlide[] = [
  {
    title: "EVO Lite Neo",
    image: "/images/vinfast/scooters/evo-lite-neo.png",
    imageAlt: "EVO Lite Neo",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "49 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "78 km",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "17 lít",
        label: "Cốp xe",
      },
      {
        value: "14.400.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/evo-lite-neo",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-evo-lite-neo.html",
  },
  {
    title: "FLAZZ MAX",
    image: "/images/vinfast/scooters/flazz-max.webp",
    imageAlt: "FLAZZ MAX",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "49 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "~87 km/lần sạc",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "1500 W",
        label: "Công suất tối đa",
      },
      {
        value: "14.990.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/flazz-max",
    detailHref: "https://vinfastauto.com/xe-may-dien-vinfast-flazz-max",
  },
  {
    title: "AMIO S",
    image: "/images/vinfast/scooters/amio-s.webp",
    imageAlt: "AMIO S",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "25 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "~65 km/lần sạc",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "800 W",
        label: "Công suất tối đa",
      },
      {
        value: "13.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/amio-s",
    detailHref: "https://vinfastauto.com/xe-may-dien-vinfast-amio-s",
  },
  {
    title: "EVO Lite",
    image: "/images/vinfast/scooters/evo-lite.png",
    imageAlt: "EVO Lite",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "49 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "~165 km/lần sạc",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "2300 W",
        label: "Công suất tối đa",
      },
      {
        value: "17.000.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/evo-lite",
    detailHref: "https://vinfastauto.com/xe-may-dien-evo",
  },
  {
    title: "Amio",
    image: "/images/vinfast/scooters/amio.webp",
    imageAlt: "Amio",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "30 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "~65 km/lần sạc",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "800 W",
        label: "Công suất tối đa",
      },
      {
        value: "13.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/amio",
    detailHref: "https://vinfastauto.com/vn_vi/xe-may-dien-vinfast-amio",
  },
  {
    title: "Viper",
    image: "/images/vinfast/scooters/viper.webp",
    imageAlt: "Viper",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "70 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "~156 km/lần sạc",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "3000 W",
        label: "Công suất tối đa",
      },
      {
        value: "39.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/viper",
    detailHref: "https://vinfastauto.com/xe-may-dien-vinfast-viper",
  },
  {
    title: "Feliz II",
    image: "/images/vinfast/scooters/feliz-ii.webp",
    imageAlt: "Feliz II",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "70 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "~156 km/lần sạc",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "3000 W",
        label: "Công suất tối đa",
      },
      {
        value: "24.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/feliz-ii",
    detailHref: "https://vinfastauto.com/xe-may-dien-vinfast-feliz-II",
  },
  {
    title: "EVO",
    image: "/images/vinfast/scooters/evo.webp",
    imageAlt: "EVO",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "70 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "~165 km/lần sạc",
        label: "Quãng đường 1 lần sạc (2 pin)",
      },
      {
        value: "12 lít",
        label: "Cốp xe",
      },
      {
        value: "19.990.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/evo",
    detailHref: "https://vinfastauto.com/xe-may-dien-evo",
  },
  {
    title: "zgoo",
    image: "/images/vinfast/scooters/zgoo.webp",
    imageAlt: "zgoo",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "39 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "70 km",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "14 lít",
        label: "Cốp xe",
      },
      {
        value: "15.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/zgoo",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-zgoo.html",
  },
  {
    title: "Flazz",
    image: "/images/vinfast/scooters/flazz.webp",
    imageAlt: "Flazz",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "39 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "135 km",
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
      },
      {
        value: "14 lít",
        label: "Cốp xe",
      },
      {
        value: "16.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/flazz",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-flazz.html",
  },
  {
    title: "Vero X",
    image: "/images/vinfast/scooters/vero-x.webp",
    imageAlt: "Vero X",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "70 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "262 km",
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
      },
      {
        value: "35 lít",
        label: "Cốp xe",
      },
      {
        value: "34.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/vero-x",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-verox.html",
  },
  {
    title: "Feliz 2025",
    image: "/images/vinfast/scooters/feliz-2025.webp",
    imageAlt: "Feliz 2025",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "70 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "262 km",
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
      },
      {
        value: "34 lít",
        label: "Cốp xe",
      },
      {
        value: "27.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/feliz-2025",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-feliz.html",
  },
  {
    title: "Evo Grand",
    image: "/images/vinfast/scooters/evo-grand.webp",
    imageAlt: "Evo Grand",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "70 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "262 km",
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
      },
      {
        value: "35 lít",
        label: "Cốp xe",
      },
      {
        value: "23.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/evo-grand",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-evo-grand.html",
  },
  {
    title: "Evo Grand Lite",
    image: "/images/vinfast/scooters/evo-grand-lite.webp",
    imageAlt: "Evo Grand Lite",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "48 km/h",
        label: "Tốc độ tối đa",
      },
      {
        value: "198 km",
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
      },
      {
        value: "35 lít",
        label: "Cốp xe",
      },
      {
        value: "19.900.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/evo-grand-lite",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-evo-grand-lite.html",
  },
  {
    title: "DrgnFly",
    image: "/images/vinfast/scooters/drgnfly.png",
    imageAlt: "DrgnFly",
    imageClass: "h-full w-full object-contain object-right",
    specs: [
      {
        value: "250 W",
        label: "Công suất động cơ",
      },
      {
        value: "110 km",
        label: "Quãng đường 1 lần sạc",
      },
      {
        value: "47,2V",
        label: "Pin Lithium Ion",
      },
      {
        value: "18.690.000 VNĐ",
        label: "Giá từ",
        highlight: true,
      },
    ],
    primaryCta: "MUA NGAY",
    secondaryCta: "XEM CHI TIẾT",
    href: "/xe-may-dien/drgnfly",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-dap-dien-drgnfly.html",
  },
];

export const VINFAST_ALL_CARS = [
  {
    name: "VF 9",
    image: "/images/vinfast/cars/vf9.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "E-SUV",
      },
      {
        label: "Số chỗ ngồi",
        value: "6-7 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "626 km",
      },
      {
        label: "Giá bán từ",
        value: "1.274.150.000 VNĐ*",
      },
    ],
    localId: "vf9",
    detailHref: "https://shop.vinfastauto.com/vn_vi/car-vf9.html",
  },
  {
    name: "VF 8 All New",
    image: "/images/vinfast/cars/vf8-all-new.png",
    specs: [
      {
        label: "Dòng xe",
        value: "D-SUV",
      },
      {
        label: "Số chỗ ngồi",
        value: "5 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "480-500 km",
      },
      {
        label: "Giá bán từ",
        value: "849.150.000 VNĐ*",
      },
    ],
    localId: "vf8-all-new",
    detailHref: "https://vinfastauto.com/vn_vi/dat-coc-xe-vf8-the-all-new-2026",
  },
  {
    name: "VF MPV 7",
    image: "/images/vinfast/cars/vf-mpv7.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "MPV",
      },
      {
        label: "Số chỗ ngồi",
        value: "7 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "450 km (NEDC)",
      },
      {
        label: "Giá bán từ",
        value: "728.910.000 VNĐ*",
      },
    ],
    localId: "vf-mpv7",
    detailHref: "https://vinfastauto.com/vn_vi/dat-coc-xe-vf-mpv7",
  },
  {
    name: "EC VAN",
    image: "/images/vinfast/cars/ec-van.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "VAN",
      },
      {
        label: "Số chỗ ngồi",
        value: "2 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "150 km",
      },
      {
        label: "Giá bán từ",
        value: "253.650.000 VNĐ*",
      },
    ],
    localId: "ec-van",
    detailHref: "https://shop.vinfastauto.com/vn_vi/vinfast-ecvan.html",
  },
  {
    name: "Minio Green",
    image: "/images/vinfast/cars/minio-green.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "MiniCar",
      },
      {
        label: "Số chỗ ngồi",
        value: "4 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "170 km (NEDC)",
      },
      {
        label: "Giá bán từ",
        value: "239.410.000 VNĐ*",
      },
    ],
    localId: "minio-green",
    detailHref: "https://shop.vinfastauto.com/vn_vi/minio-green.html",
  },
  {
    name: "Herio Green",
    image: "/images/vinfast/cars/herio-green.png",
    specs: [
      {
        label: "Dòng xe",
        value: "A-SUV",
      },
      {
        label: "Số chỗ ngồi",
        value: "5 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "326 km (NEDC)",
      },
      {
        label: "Giá bán từ",
        value: "426.310.000 VNĐ*",
      },
    ],
    localId: "herio-green",
    detailHref: "https://shop.vinfastauto.com/vn_vi/herio-green.html",
  },
  {
    name: "Nerio Green",
    image: "/images/vinfast/cars/nerio-green.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "B-SUV",
      },
      {
        label: "Số chỗ ngồi",
        value: "5 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "318,6 km (NEDC)",
      },
      {
        label: "Giá từ",
        value: "668.000.000 VNĐ",
      },
    ],
    localId: "nerio-green",
    detailHref: "https://shop.vinfastauto.com/vn_vi/nerio-green.html",
  },
  {
    name: "Limo Green",
    image: "/images/vinfast/cars/limo-green.png",
    specs: [
      {
        label: "Dòng xe",
        value: "MPV",
      },
      {
        label: "Số chỗ ngồi",
        value: "7 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "450 km (NEDC)",
      },
      {
        label: "Giá bán từ",
        value: "666.610.000 VNĐ*",
      },
    ],
    localId: "limo-green",
    detailHref: "https://shop.vinfastauto.com/vn_vi/limo-green.html",
  },
  {
    name: "VF 3",
    image: "/images/vinfast/cars/vf3.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "MiniCar",
      },
      {
        label: "Số chỗ ngồi",
        value: "4 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "210 km (NEDC)",
      },
      {
        label: "Giá bán từ",
        value: "268.780.000 VNĐ*",
      },
    ],
    localId: "vf3",
    detailHref: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf3.html",
  },
  {
    name: "VF 5",
    image: "/images/vinfast/cars/vf5.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "A-SUV",
      },
      {
        label: "Số chỗ ngồi",
        value: "5 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "326,4 km (NEDC)",
      },
      {
        label: "Giá bán từ",
        value: "470.810.000 VNĐ*",
      },
    ],
    localId: "vf5",
    detailHref: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf5.html",
  },
  {
    name: "VF 6",
    image: "/images/vinfast/cars/vf6.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "B-SUV",
      },
      {
        label: "Số chỗ ngồi",
        value: "5 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "480 km (NEDC)",
      },
      {
        label: "Giá bán từ",
        value: "613.210.000 VNĐ*",
      },
    ],
    localId: "vf6",
    detailHref: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf6.html",
  },
  {
    name: "VF 7",
    image: "/images/vinfast/cars/vf7.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "C-SUV",
      },
      {
        label: "Số chỗ ngồi",
        value: "5 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "496 km",
      },
      {
        label: "Giá bán từ",
        value: "702.210.000 VNĐ*",
      },
    ],
    localId: "vf7",
    detailHref: "https://shop.vinfastauto.com/vn_vi/dat-coc-xe-dien-vf7.html",
  },
  {
    name: "VF 8",
    image: "/images/vinfast/cars/vf8.webp",
    specs: [
      {
        label: "Dòng xe",
        value: "D-SUV",
      },
      {
        label: "Số chỗ ngồi",
        value: "5 chỗ",
      },
      {
        label: "Quãng đường lên tới",
        value: "471 km",
      },
      {
        label: "Giá bán từ",
        value: "866.150.000 VNĐ*",
      },
    ],
    localId: "vf8",
    detailHref: "https://shop.vinfastauto.com/vn_vi/car-vf8.html",
  },
] as const;

export const VINFAST_ALL_SCOOTERS = [
  {
    name: "EVO Lite Neo",
    image: "/images/vinfast/scooters/evo-lite-neo.png",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "49 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "78 km",
      },
      {
        label: "Cốp xe",
        value: "17 lít",
      },
      {
        label: "Giá từ",
        value: "14.400.000 VNĐ",
      },
    ],
    localId: "evo-lite-neo",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-evo-lite-neo.html",
  },
  {
    name: "FLAZZ MAX",
    image: "/images/vinfast/scooters/flazz-max.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "49 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "~87 km/lần sạc",
      },
      {
        label: "Công suất tối đa",
        value: "1500 W",
      },
      {
        label: "Giá từ",
        value: "14.990.000 VNĐ",
      },
    ],
    localId: "flazz-max",
    detailHref: "https://vinfastauto.com/xe-may-dien-vinfast-flazz-max",
  },
  {
    name: "AMIO S",
    image: "/images/vinfast/scooters/amio-s.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "25 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "~65 km/lần sạc",
      },
      {
        label: "Công suất tối đa",
        value: "800 W",
      },
      {
        label: "Giá từ",
        value: "13.900.000 VNĐ",
      },
    ],
    localId: "amio-s",
    detailHref: "https://vinfastauto.com/xe-may-dien-vinfast-amio-s",
  },
  {
    name: "EVO Lite",
    image: "/images/vinfast/scooters/evo-lite.png",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "49 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "~165 km/lần sạc",
      },
      {
        label: "Công suất tối đa",
        value: "2300 W",
      },
      {
        label: "Giá từ",
        value: "17.000.000 VNĐ",
      },
    ],
    localId: "evo-lite",
    detailHref: "https://vinfastauto.com/xe-may-dien-evo",
  },
  {
    name: "Amio",
    image: "/images/vinfast/scooters/amio.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "30 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "~65 km/lần sạc",
      },
      {
        label: "Công suất tối đa",
        value: "800 W",
      },
      {
        label: "Giá từ",
        value: "13.900.000 VNĐ",
      },
    ],
    localId: "amio",
    detailHref: "https://vinfastauto.com/vn_vi/xe-may-dien-vinfast-amio",
  },
  {
    name: "Viper",
    image: "/images/vinfast/scooters/viper.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "70 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "~156 km/lần sạc",
      },
      {
        label: "Công suất tối đa",
        value: "3000 W",
      },
      {
        label: "Giá từ",
        value: "39.900.000 VNĐ",
      },
    ],
    localId: "viper",
    detailHref: "https://vinfastauto.com/xe-may-dien-vinfast-viper",
  },
  {
    name: "Feliz II",
    image: "/images/vinfast/scooters/feliz-ii.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "70 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "~156 km/lần sạc",
      },
      {
        label: "Công suất tối đa",
        value: "3000 W",
      },
      {
        label: "Giá từ",
        value: "24.900.000 VNĐ",
      },
    ],
    localId: "feliz-ii",
    detailHref: "https://vinfastauto.com/xe-may-dien-vinfast-feliz-II",
  },
  {
    name: "EVO",
    image: "/images/vinfast/scooters/evo.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "70 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc (2 pin)",
        value: "~165 km/lần sạc",
      },
      {
        label: "Cốp xe",
        value: "12 lít",
      },
      {
        label: "Giá từ",
        value: "19.990.000 VNĐ",
      },
    ],
    localId: "evo",
    detailHref: "https://vinfastauto.com/xe-may-dien-evo",
  },
  {
    name: "zgoo",
    image: "/images/vinfast/scooters/zgoo.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "39 km/h",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "70 km",
      },
      {
        label: "Cốp xe",
        value: "14 lít",
      },
      {
        label: "Giá từ",
        value: "15.900.000 VNĐ",
      },
    ],
    localId: "zgoo",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-zgoo.html",
  },
  {
    name: "Flazz",
    image: "/images/vinfast/scooters/flazz.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "39 km/h",
      },
      {
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
        value: "135 km",
      },
      {
        label: "Cốp xe",
        value: "14 lít",
      },
      {
        label: "Giá từ",
        value: "16.900.000 VNĐ",
      },
    ],
    localId: "flazz",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-flazz.html",
  },
  {
    name: "Vero X",
    image: "/images/vinfast/scooters/vero-x.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "70 km/h",
      },
      {
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
        value: "262 km",
      },
      {
        label: "Cốp xe",
        value: "35 lít",
      },
      {
        label: "Giá từ",
        value: "34.900.000 VNĐ",
      },
    ],
    localId: "vero-x",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-verox.html",
  },
  {
    name: "Feliz 2025",
    image: "/images/vinfast/scooters/feliz-2025.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "70 km/h",
      },
      {
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
        value: "262 km",
      },
      {
        label: "Cốp xe",
        value: "34 lít",
      },
      {
        label: "Giá từ",
        value: "27.900.000 VNĐ",
      },
    ],
    localId: "feliz-2025",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-feliz.html",
  },
  {
    name: "Evo Grand",
    image: "/images/vinfast/scooters/evo-grand.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "70 km/h",
      },
      {
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
        value: "262 km",
      },
      {
        label: "Cốp xe",
        value: "35 lít",
      },
      {
        label: "Giá từ",
        value: "23.900.000 VNĐ",
      },
    ],
    localId: "evo-grand",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-evo-grand.html",
  },
  {
    name: "Evo Grand Lite",
    image: "/images/vinfast/scooters/evo-grand-lite.webp",
    specs: [
      {
        label: "Tốc độ tối đa",
        value: "48 km/h",
      },
      {
        label: "Quãng đường đi được 1 lần sạc (2 pin)",
        value: "198 km",
      },
      {
        label: "Cốp xe",
        value: "35 lít",
      },
      {
        label: "Giá từ",
        value: "19.900.000 VNĐ",
      },
    ],
    localId: "evo-grand-lite",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-may-dien-evo-grand-lite.html",
  },
  {
    name: "DrgnFly",
    image: "/images/vinfast/scooters/drgnfly.png",
    specs: [
      {
        label: "Công suất động cơ",
        value: "250 W",
      },
      {
        label: "Quãng đường 1 lần sạc",
        value: "110 km",
      },
      {
        label: "Pin Lithium Ion",
        value: "47,2V",
      },
      {
        label: "Giá từ",
        value: "18.690.000 VNĐ",
      },
    ],
    localId: "drgnfly",
    detailHref: "https://shop.vinfastauto.com/vn_vi/xe-dap-dien-drgnfly.html",
  },
] as const;

export const VINFAST_SYNCED_AT = "2026-06-23T10:01:37.908Z";
