// Auto-generated — scripts/generate-vinfast-galleries.mjs
// Source: scripts/vinfast-gallery-images.json
// Last synced: 2026-06-23T10:09:10.103Z

import type { CarModel } from "./cars";

export const CAR_GALLERIES: Record<string, string[]> = {
  vf9: [
    "/images/vinfast/gallery/vf9/hero.webp",
    "/images/vinfast/gallery/vf9/img-top.webp",
    "/images/vinfast/gallery/vf9/img-vf9-top-side.webp",
    "/images/vinfast/gallery/vf9/lead-hero-img.webp",
    "/images/vinfast/gallery/vf9/CE1V.webp",
    "/images/vinfast/gallery/vf9/CE1W.webp",
    "/images/vinfast/gallery/vf9/CE11.webp",
    "/images/vinfast/gallery/vf9/CE22.webp",
    "/images/vinfast/gallery/vf9/CE18.webp",
    "/images/vinfast/gallery/vf9/CE17.webp",
    "/images/vinfast/gallery/vf9/CE1M.webp",
    "/images/vinfast/gallery/vf9/interior-first-sight.webp",
    "/images/vinfast/gallery/vf9/int-preview-1.webp",
    "/images/vinfast/gallery/vf9/int-slide-1.webp",
    "/images/vinfast/gallery/vf9/int-preview-2.webp",
    "/images/vinfast/gallery/vf9/int-slide-2.webp",
    "/images/vinfast/gallery/vf9/int-preview-3.webp",
    "/images/vinfast/gallery/vf9/int-slide-3.webp",
    "/images/vinfast/gallery/vf9/int-preview-4.webp",
    "/images/vinfast/gallery/vf9/int-slide-4.webp",
    "/images/vinfast/gallery/vf9/img-banner-top.webp",
    "/images/vinfast/gallery/vf9/vf9-preview.webp",
  ],
  "vf8-all-new": [
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-13.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-15.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-21.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-23.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-17.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-19.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-14.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-16.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-18.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-20.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-22.png",
    "https://vinfastauto.com/themes/porto/img/vf8-new-product/color/car/VF8PH-24.png",
  ],
  "ec-van": [
    "/images/vinfast/gallery/ec-van/banner.webp",
    "/images/vinfast/gallery/ec-van/banner-sp.webp",
    "/images/vinfast/gallery/ec-van/spec.webp",
    "/images/vinfast/gallery/ec-van/ecvan-jade.webp",
    "/images/vinfast/gallery/ec-van/ecvan-jade-01.webp",
    "/images/vinfast/gallery/ec-van/ecvan-jade-02.webp",
    "/images/vinfast/gallery/ec-van/ecvan-jade-03.webp",
    "/images/vinfast/gallery/ec-van/ecvan-white.webp",
    "/images/vinfast/gallery/ec-van/ecvan-white-01.webp",
    "/images/vinfast/gallery/ec-van/ecvan-white-02.webp",
    "/images/vinfast/gallery/ec-van/ecvan-white-03.webp",
    "/images/vinfast/gallery/ec-van/ecvan-red.webp",
    "/images/vinfast/gallery/ec-van/ecvan-red-01.webp",
    "/images/vinfast/gallery/ec-van/ecvan-red-02.webp",
    "/images/vinfast/gallery/ec-van/ecvan-red-03.webp",
    "/images/vinfast/gallery/ec-van/ecvan-yellow.webp",
    "/images/vinfast/gallery/ec-van/ecvan-yellow-01.webp",
    "/images/vinfast/gallery/ec-van/ecvan-yellow-02.webp",
    "/images/vinfast/gallery/ec-van/ecvan-yellow-03.webp",
    "/images/vinfast/gallery/ec-van/jade.png",
    "/images/vinfast/gallery/ec-van/white.png",
    "/images/vinfast/gallery/ec-van/red.png",
    "/images/vinfast/gallery/ec-van/yellow.png",
    "/images/vinfast/gallery/ec-van/ecvan-img-01.webp",
  ],
  "nerio-green": [
    "/images/vinfast/gallery/nerio-green/nerio-green.png",
    "/images/vinfast/gallery/nerio-green/nerio-img-01.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-01-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-02.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-02-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-03.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-03-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-04.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-04-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-05.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-05-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-06.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-06-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-07.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-07-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-08.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-08-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-09.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-09-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-10.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-10-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-11.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-11-sp.webp",
    "/images/vinfast/gallery/nerio-green/nerio-img-12.webp",
  ],
  vf3: [
    "/images/vinfast/gallery/vf3/VF3_Interior_Hero.jpg",
    "/images/vinfast/gallery/vf3/vf3section-4.jpg",
    "/images/vinfast/gallery/vf3/vf3section-4.1.jpg",
    "/images/vinfast/gallery/vf3/vf3section-5.jpg",
    "/images/vinfast/gallery/vf3/vf3.jpg",
    "/images/vinfast/gallery/vf3/vf3-1.png",
    "/images/vinfast/gallery/vf3/VF3_Rear-2034_Driver_Side_Wheel_Cover1.png",
    "/images/vinfast/gallery/vf3/F1.png",
    "/images/vinfast/gallery/vf3/F1.png",
    "/images/vinfast/gallery/vf3/F1.png",
    "/images/vinfast/gallery/vf3/F1.png",
    "/images/vinfast/gallery/vf3/F1.png",
    "/images/vinfast/gallery/vf3/F1.png",
    "/images/vinfast/gallery/vf3/F1.png",
    "/images/vinfast/gallery/vf3/F1.png",
    "/images/vinfast/gallery/vf3/F1.png",
  ],
  vf5: [
    "/images/vinfast/gallery/vf5/hero.webp",
    "/images/vinfast/gallery/vf5/img-maintop.jpg",
    "/images/vinfast/gallery/vf5/hero-01.webp",
    "/images/vinfast/gallery/vf5/Main.webp",
    "/images/vinfast/gallery/vf5/Main-1.webp",
    "/images/vinfast/gallery/vf5/Main-2.webp",
    "/images/vinfast/gallery/vf5/Main-3.webp",
    "/images/vinfast/gallery/vf5/Main-4.webp",
    "/images/vinfast/gallery/vf5/Main-5.webp",
    "/images/vinfast/gallery/vf5/Main-6.webp",
    "/images/vinfast/gallery/vf5/Main-7.webp",
    "/images/vinfast/gallery/vf5/Main-8.webp",
    "/images/vinfast/gallery/vf5/i-10.webp",
    "/images/vinfast/gallery/vf5/i-12.webp",
    "/images/vinfast/gallery/vf5/i-15.webp",
    "/images/vinfast/gallery/vf5/i-11.webp",
    "/images/vinfast/gallery/vf5/10.webp",
    "/images/vinfast/gallery/vf5/12.webp",
    "/images/vinfast/gallery/vf5/15.webp",
    "/images/vinfast/gallery/vf5/11.webp",
    "/images/vinfast/gallery/vf5/place-1.webp",
    "/images/vinfast/gallery/vf5/place-2.webp",
    "/images/vinfast/gallery/vf5/place-3.webp",
    "/images/vinfast/gallery/vf5/place-4.webp",
  ],
  vf6: [
    "/images/vinfast/gallery/vf6/VF6-banner.webp",
    "/images/vinfast/gallery/vf6/bottom-banner.webp",
    "/images/vinfast/gallery/vf6/VF6-banner-1.webp",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-00.webp",
    "/images/vinfast/gallery/vf6/exterior-1.webp",
    "/images/vinfast/gallery/vf6/exterior-2.webp",
    "/images/vinfast/gallery/vf6/exterior-3.webp",
    "/images/vinfast/gallery/vf6/interior-vf6-1.jpg",
    "/images/vinfast/gallery/vf6/interior-vf6-2.jpg",
    "/images/vinfast/gallery/vf6/technology-vf6-3.jpg",
    "/images/vinfast/gallery/vf6/technology-vf6-4.jpg",
    "/images/vinfast/gallery/vf6/naturel.webp",
    "/images/vinfast/gallery/vf6/xe.webp",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-10.webp",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-11.webp",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-12.webp",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-13.webp",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-01.jpg",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-02.jpg",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-03.jpg",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-04.jpg",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-05.jpg",
    "/images/vinfast/gallery/vf6/VF6-Lifestyle-06.jpg",
  ],
  vf7: [
    "/images/vinfast/gallery/vf7/vf7-hero-banner.webp",
    "/images/vinfast/gallery/vf7/vf7-lead-banner.webp",
    "/images/vinfast/gallery/vf7/product-CE1M.webp",
    "/images/vinfast/gallery/vf7/product-CE1V.webp",
    "/images/vinfast/gallery/vf7/product-CE1W.webp",
    "/images/vinfast/gallery/vf7/product-CE18.webp",
    "/images/vinfast/gallery/vf7/product-CE11.webp",
    "/images/vinfast/gallery/vf7/vf7-hero-banner-sp.webp",
    "/images/vinfast/gallery/vf7/vf7-hero-car.webp",
    "/images/vinfast/gallery/vf7/vf7-tuy-chon-gia.webp",
    "/images/vinfast/gallery/vf7/vf7-slide-in-croped.webp",
    "/images/vinfast/gallery/vf7/vf7-img-tech.webp",
    "/images/vinfast/gallery/vf7/vf7-masterpiece-1.webp",
    "/images/vinfast/gallery/vf7/vf7-masterpiece-2.webp",
    "/images/vinfast/gallery/vf7/vf7-masterpiece-3.webp",
    "/images/vinfast/gallery/vf7/vf7-masterpiece-4.webp",
    "/images/vinfast/gallery/vf7/vf7-masterpiece-5.webp",
    "/images/vinfast/gallery/vf7/vf7-noi-that-overview.webp",
    "/images/vinfast/gallery/vf7/vf7-noi-that-compare-left.webp",
    "/images/vinfast/gallery/vf7/vf7-noi-that-compare-right.webp",
    "/images/vinfast/gallery/vf7/vf7-tien-nghi-1.webp",
    "/images/vinfast/gallery/vf7/vf7-tien-nghi-2.webp",
    "/images/vinfast/gallery/vf7/vf7-tien-nghi-3.webp",
    "/images/vinfast/gallery/vf7/vf7-tien-nghi-4.webp",
  ],
  vf8: [
    "/images/vinfast/gallery/vf8/img-top.jpg",
    "/images/vinfast/gallery/vf8/banner.webp",
    "/images/vinfast/gallery/vf8/img-top.webp",
    "/images/vinfast/gallery/vf8/product-CE1V.webp",
    "/images/vinfast/gallery/vf8/product-CE1W.webp",
    "/images/vinfast/gallery/vf8/product-CE11.webp",
    "/images/vinfast/gallery/vf8/product-CE22.webp",
    "/images/vinfast/gallery/vf8/product-CE18.webp",
    "/images/vinfast/gallery/vf8/product-CE17.webp",
    "/images/vinfast/gallery/vf8/product-CE1M.webp",
    "/images/vinfast/gallery/vf8/product-2927.webp",
    "/images/vinfast/gallery/vf8/product-171V.webp",
    "/images/vinfast/gallery/vf8/product-1V18.webp",
    "/images/vinfast/gallery/vf8/product-2911.webp",
    "/images/vinfast/gallery/vf8/interior-img1.webp",
    "/images/vinfast/gallery/vf8/interior-img2.webp",
    "/images/vinfast/gallery/vf8/interior-img3.webp",
    "/images/vinfast/gallery/vf8/interior-img4.webp",
    "/images/vinfast/gallery/vf8/interior-img5.webp",
    "/images/vinfast/gallery/vf8/thietkekdh.webp",
    "/images/vinfast/gallery/vf8/guong.webp",
    "/images/vinfast/gallery/vf8/panorama.webp",
    "/images/vinfast/gallery/vf8/vf8eco.webp",
    "/images/vinfast/gallery/vf8/vf8-lux.webp",
  ],
};

/** Hero gallery for car detail — curated PDP shots, then color variants, then catalog image. */
export function getCarGallery(car: CarModel): string[] {
  const curated = CAR_GALLERIES[car.id];
  const colorImages = car.colors.map((c) => c.image).filter(Boolean) as string[];
  const base = curated?.length ? curated : [];
  const merged = [...base];
  for (const img of colorImages) {
    if (!merged.includes(img)) merged.push(img);
  }
  if (!merged.includes(car.image)) merged.unshift(car.image);
  const unique = [...new Set(merged)];
  return unique.length ? unique : [car.image];
}
