// Auto-generated by scripts/generate-car-detail-patch.mjs
// Nội dung PDP chỉnh tay — ưu tiên hơn vinfast-detail-overrides.ts
// Last synced: 2026-06-26T13:01:02.679Z

import type { CarDetail } from "./car-details";

/** VF 8 / VF 8 All New — chỉnh tay chi tiết */
import { VF8_DETAIL_PATCHES } from "./vinfast-vf8-detail-patch";

const GENERATED_PATCHES: Partial<Record<string, Partial<CarDetail>>> = {
  "vf-mpv7": {
    tagline: "VF MPV 7",
    badges: ["Quãng đường 450 km", "Công suất 201 hp / 280 Nm"],
    slogan: "Gia đình sum vầy — MPV điện 7 chỗ",
    overview: {
      title: "VF MPV 7 — Gia đình sum vầy, hành trình trọn vẹn",
      subtitle:
        "MPV điện 7 chỗ với quãng đường 450 km (NEDC), không gian rộng rãi cho cả gia đình.",
      bullets: [
        "Quãng đường 450 km (NEDC)",
        "Công suất 150 kW / Mô-men 280 Nm",
        "Sạc nhanh DC 80 kW — 30 phút (10%-70%)",
      ],
      image: "/images/vinfast/cars/vf-mpv7.webp",
    },
    exterior: [
      {
        title: "Thiết kế ngoại thất hiện đại",
        desc: "VF MPV 7 sở hữu ngôn ngữ thiết kế trẻ trung, khí động học tối ưu và đèn LED đặc trưng VinFast.",
        image: "/images/vinfast/cars/vf-mpv7.webp",
      },
      {
        title: "Đèn chiếu sáng LED thông minh",
        desc: "Hệ thống đèn full-LED tăng khả năng quan sát ban đêm và tạo dấu ấn nhận diện mạnh mẽ.",
        image: "/images/vinfast/cars/vf-mpv7.webp",
      },
      {
        title: "La-zăng hợp kim thể thao",
        desc: "Mâm xe hợp kim thiết kế đa chấu, tăng vẻ thể thao và ổn định khi vận hành.",
        image: "/images/vinfast/cars/vf-mpv7.webp",
      },
      {
        title: "Cảm biến hỗ trợ quan sát",
        desc: "Camera và cảm biến hỗ trợ quan sát, đỗ xe an toàn trong không gian chật hẹp.",
        image: "/images/vinfast/cars/vf-mpv7.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin VF MPV 7 thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/cars/vf-mpv7.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/cars/vf-mpv7.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image: "/images/vinfast/cars/vf-mpv7.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/cars/vf-mpv7.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "VF MPV 7 tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 450 km — công suất 201 hp",
      image: "/images/vinfast/cars/vf-mpv7.webp",
      features: [
        {
          title: "Công suất 201 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 280 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 450 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 30 phút (10%-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên VF MPV 7",
      image: "/images/vinfast/cars/vf-mpv7.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho VF MPV 7 — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 450,
      power: 201,
      torque: 280,
      acceleration: "8.0 giây (0-100 km/h)",
      topSpeed: 175,
      fastCharge: "30 phút (10%-70%)",
    },
    variants: [
      {
        id: "vf-mpv-7",
        name: "VF MPV 7",
        price: 819000000,
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "4740 x 1872 x 1734",
          },
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2840",
          },
          {
            label: "Khoảng sáng gầm xe (mm)",
            value: "185",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "150",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "280",
          },
          {
            label: "Quãng đường chạy (NEDC) (km)",
            value: "450",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "60,13",
          },
          {
            label: "Công suất sạc nhanh DC tối đa (kW)",
            value: "80",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "30 phút (10%-70%)",
          },
          {
            label: "Dẫn động",
            value: "FWD/Cầu trước",
          },
          {
            label: "Kích thước la-zăng",
            value: "Mâm hợp kim 19 inch",
          },
        ],
      },
    ],
  },
  "ec-van": {
    tagline: "EC VAN",
    badges: ["Quãng đường 175 km", "Công suất 40 hp / 110 Nm"],
    slogan: "Linh hoạt lưu thông nội đô, vận hành êm ái, giảm chi phí vận hành, tối đa lợi nhuận",
    overview: {
      title: "Vận tải đa năng, tiện dụng, sinh lời",
      subtitle:
        "Linh hoạt lưu thông nội đô, vận hành êm ái, giảm chi phí vận hành, tối đa lợi nhuận",
      bullets: [
        "Quãng đường di chuyển (NEDC) 175 km",
        "Mô men xoắn cực đại 110 Nm Quãng đường di chuyển (NEDC) 175 km/sạc đầy",
        "Công suất tối đa 30 kW",
      ],
      image: "/images/vinfast/cars/ec-van.webp",
    },
    exterior: [
      {
        title: "Thiết kế ngoại thất hiện đại",
        desc: "EC VAN sở hữu ngôn ngữ thiết kế trẻ trung, khí động học tối ưu và đèn LED đặc trưng VinFast.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-banner.webp",
      },
      {
        title: "Đèn chiếu sáng LED thông minh",
        desc: "Hệ thống đèn full-LED tăng khả năng quan sát ban đêm và tạo dấu ấn nhận diện mạnh mẽ.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-banner-sp.webp",
      },
      {
        title: "La-zăng hợp kim thể thao",
        desc: "Mâm xe hợp kim thiết kế đa chấu, tăng vẻ thể thao và ổn định khi vận hành.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-spec.webp",
      },
      {
        title: "Cảm biến hỗ trợ quan sát",
        desc: "Camera và cảm biến hỗ trợ quan sát, đỗ xe an toàn trong không gian chật hẹp.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-ecvan-jade.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin EC VAN thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-ecvan-jade-01.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-ecvan-jade-02.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-ecvan-jade-03.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-ecvan-white.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "EC VAN tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 175 km — công suất 40 hp",
      image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-banner-sp.webp",
      features: [
        {
          title: "Công suất 40 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 110 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 175 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 45 phút (10-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên EC VAN",
      image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-spec.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho EC VAN — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 175,
      power: 40,
      torque: 110,
      acceleration: "14.0 giây (0-100 km/h)",
      topSpeed: 160,
      fastCharge: "45 phút (10-70%)",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "3.767 x 1.680 x 1.790 ",
          },
        ],
      },
    ],
  },
  "minio-green": {
    tagline: "MINIO GREEN",
    badges: ["Quãng đường 210 km", "Công suất 40 hp / 65 Nm"],
    slogan: "Khởi nghiệp trong tầm tay — MiniCar điện đô thị gọn nhẹ",
    overview: {
      title: "MINIO GREEN - KHỞI NGHIỆP TRONG TẦM TAY",
      subtitle: "Sở hữu kích thước gọn, vừa vặn với mọi ngõ hẻm, từ đô thị đến nông thôn Việt Nam.",
      bullets: [
        "Quãng đường 210 km (NEDC)",
        "Công suất 30 kW / Mô-men 65 Nm",
        "Dải màu trẻ trung lên tới 14 màu",
      ],
      image: "/images/vinfast/cars/minio-green.webp",
    },
    exterior: [
      {
        title: "Ưu điểm, điểm nổi bật",
        desc: "Vận hành đơn giản, tối ưu phù hợp cho người mới sử dụng EV.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
      {
        title: "Dải màu trẻ trung",
        desc: "Minio Green chính thức là chiến thần vỏn vẹn 2 cửa với lên tới 14 tùy chọn màu sắc cá tính.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin Minio Green thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "Minio Green tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 210 km — công suất 40 hp",
      image: "/images/vinfast/cars/minio-green.webp",
      features: [
        {
          title: "Công suất 40 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 65 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 210 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 40 phút (10-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên Minio Green",
      image: "/images/vinfast/cars/minio-green.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho Minio Green — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 210,
      power: 40,
      torque: 65,
      acceleration: "15.0 giây (0-100 km/h)",
      topSpeed: 160,
      fastCharge: "40 phút (10-70%)",
    },
    variants: [
      {
        id: "minio-green",
        name: "Minio Green",
        price: 269000000,
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2065",
          },
          {
            label: "Khoảng sáng gầm xe (mm)",
            value: "166,3",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "30",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "65",
          },
          {
            label: "Quãng đường chạy (NEDC) (km/lần sạc đầy)",
            value: "210",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "18,3",
          },
          {
            label: "Dẫn động",
            value: "RWD/Cầu sau",
          },
        ],
      },
    ],
  },
  "herio-green": {
    tagline: "HERIO GREEN",
    badges: ["Quãng đường 326 km", "Công suất 134 hp / 135 Nm"],
    slogan: "A-SUV điện — trọn vẹn trải nghiệm cùng Herio",
    overview: {
      title: "HERIO GREEN — A-SUV điện đô thị",
      subtitle:
        "Herio Green sở hữu thiết kế hiện đại, trẻ trung với các lựa chọn phối màu nội ngoại thất cá tính.",
      bullets: ["Quãng đường 326 km (NEDC)", "Công suất 100 kW / Mô-men 135 Nm", "Pin 37,23 kWh"],
      image: "/images/vinfast/cars/herio-green.webp",
    },
    exterior: [
      {
        title: "Thiết kế ngoại thất hiện đại",
        desc: "Herio Green sở hữu ngôn ngữ thiết kế trẻ trung, khí động học tối ưu và đèn LED đặc trưng VinFast.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
      {
        title: "Đèn chiếu sáng LED thông minh",
        desc: "Hệ thống đèn full-LED tăng khả năng quan sát ban đêm và tạo dấu ấn nhận diện mạnh mẽ.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
      {
        title: "La-zăng hợp kim thể thao",
        desc: "Mâm xe hợp kim thiết kế đa chấu, tăng vẻ thể thao và ổn định khi vận hành.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
      {
        title: "Cảm biến hỗ trợ quan sát",
        desc: "Camera và cảm biến hỗ trợ quan sát, đỗ xe an toàn trong không gian chật hẹp.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin Herio Green thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "Herio Green tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 326 km — công suất 134 hp",
      image: "/images/vinfast/cars/herio-green.webp",
      features: [
        {
          title: "Công suất 134 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 135 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 326 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 30 phút (10-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên Herio Green",
      image: "/images/vinfast/cars/herio-green.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho Herio Green — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 326,
      power: 134,
      torque: 135,
      acceleration: "10.9 giây (0-100 km/h)",
      topSpeed: 160,
      fastCharge: "30 phút (10-70%)",
    },
    variants: [
      {
        id: "herio-green",
        name: "Herio Green",
        price: 499000000,
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2514",
          },
          {
            label: "Khoảng sáng gầm xe (mm)",
            value: "160",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "100",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "135",
          },
          {
            label: "Quãng đường chạy (NEDC) (km)",
            value: "326",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "37,23",
          },
        ],
      },
    ],
  },
  "nerio-green": {
    tagline: "NERIO GREEN",
    badges: ["Quãng đường 319 km", "Công suất 201 hp / 250 Nm"],
    slogan: "SUV điện B-SUV công nghệ và tiện nghi",
    overview: {
      title: "SUV điện B-SUV công nghệ và tiện nghi",
      subtitle: "SUV điện B-SUV công nghệ và tiện nghi",
      bullets: [
        "Quãng đường chạy (NEDC) 318,6 km",
        "Mô men xoắn cực đại 242 Nm Quãng đường chạy (NEDC) 318,6 km/lần sạc đầy",
        "Công suất tối đa 110 kW",
      ],
      image: "/images/vinfast/cars/nerio-green.webp",
    },
    exterior: [
      {
        title: "Thiết kế ngoại thất hiện đại",
        desc: "Nerio Green sở hữu ngôn ngữ thiết kế trẻ trung, khí động học tối ưu và đèn LED đặc trưng VinFast.",
        image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-green.webp",
      },
      {
        title: "Đèn chiếu sáng LED thông minh",
        desc: "Hệ thống đèn full-LED tăng khả năng quan sát ban đêm và tạo dấu ấn nhận diện mạnh mẽ.",
        image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-01.webp",
      },
      {
        title: "La-zăng hợp kim thể thao",
        desc: "Mâm xe hợp kim thiết kế đa chấu, tăng vẻ thể thao và ổn định khi vận hành.",
        image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-01-sp.webp",
      },
      {
        title: "Cảm biến hỗ trợ quan sát",
        desc: "Camera và cảm biến hỗ trợ quan sát, đỗ xe an toàn trong không gian chật hẹp.",
        image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-02.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin Nerio Green thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-02-sp.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-03.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-03-sp.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-04.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "Nerio Green tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 319 km — công suất 201 hp",
      image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-01.webp",
      features: [
        {
          title: "Công suất 201 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 250 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 319 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 30 phút (10-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên Nerio Green",
      image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-01-sp.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho Nerio Green — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 319,
      power: 201,
      torque: 250,
      acceleration: "8.5 giây (0-100 km/h)",
      topSpeed: 175,
      fastCharge: "30 phút (10-70%)",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "4300 x 1768 x 1615 ",
          },
        ],
      },
    ],
  },
  "limo-green": {
    tagline: "LIMO GREEN",
    badges: ["Quãng đường 450 km", "Công suất 201 hp / 310 Nm"],
    slogan: "Rộng mở không gian — MPV điện 7 chỗ",
    overview: {
      title: "LIMO GREEN — Rộng mở không gian, kéo dài hành trình",
      subtitle: "Xe điện 7 chỗ phù hợp gia đình đông người và vận doanh vận tải đa năng.",
      bullets: ["Quãng đường 450 km (NEDC)", "Công suất 150 kW", "7 chỗ — chiều dài cơ sở 2840 mm"],
      image: "/images/vinfast/cars/limo-green.webp",
    },
    exterior: [
      {
        title: "Thiết kế ngoại thất hiện đại",
        desc: "Limo Green sở hữu ngôn ngữ thiết kế trẻ trung, khí động học tối ưu và đèn LED đặc trưng VinFast.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
      {
        title: "Đèn chiếu sáng LED thông minh",
        desc: "Hệ thống đèn full-LED tăng khả năng quan sát ban đêm và tạo dấu ấn nhận diện mạnh mẽ.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
      {
        title: "La-zăng hợp kim thể thao",
        desc: "Mâm xe hợp kim thiết kế đa chấu, tăng vẻ thể thao và ổn định khi vận hành.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
      {
        title: "Cảm biến hỗ trợ quan sát",
        desc: "Camera và cảm biến hỗ trợ quan sát, đỗ xe an toàn trong không gian chật hẹp.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin Limo Green thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "Limo Green tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 450 km — công suất 201 hp",
      image: "/images/vinfast/cars/limo-green.webp",
      features: [
        {
          title: "Công suất 201 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 310 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 450 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 30 phút (10%-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên Limo Green",
      image: "/images/vinfast/cars/limo-green.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho Limo Green — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 450,
      power: 201,
      torque: 310,
      acceleration: "8.5 giây (0-100 km/h)",
      topSpeed: 175,
      fastCharge: "30 phút (10%-70%)",
    },
    variants: [
      {
        id: "limo-green",
        name: "Limo Green",
        price: 749000000,
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2840",
          },
          {
            label: "Chiều rộng (mm)",
            value: "1872",
          },
          {
            label: "Sức chứa",
            value: "7 chỗ",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "150",
          },
          {
            label: "Quãng đường chạy (NEDC) (km)",
            value: "450",
          },
          {
            label: "Khoảng sáng gầm xe (mm)",
            value: "180",
          },
          {
            label: "Kích thước la-zăng",
            value: "18 inch",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "30 phút (10%-70%)",
          },
        ],
      },
    ],
  },
  vf3: {
    tagline: "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn, linh hoạt, tối ưu quãng",
    badges: ["Quãng đường 210 km", "Công suất 40 hp / 110 Nm"],
    slogan:
      "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn, linh hoạt, tối ưu quãng đường di chuyển trong đô thị.",
    overview: {
      title: "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn",
      subtitle:
        "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn, linh hoạt, tối ưu quãng đường di chuyển trong đô thị.",
      bullets: [
        "Quãng đường 210 km mỗi lần sạc đầy",
        "Công suất 40 hp — mô-men xoắn 110 Nm",
        "Tăng tốc 19.3 giây (0-100 km/h)",
        "4 chỗ ngồi — pin LFP an toàn",
      ],
      image: "/images/vinfast/cars/vf3.webp",
    },
    exterior: [
      {
        title: "Thiết kế ngoại thất hiện đại",
        desc: "VF 3 sở hữu ngôn ngữ thiết kế trẻ trung, khí động học tối ưu và đèn LED đặc trưng VinFast.",
        image: "/images/vinfast/gallery/vf3/reserves-VF3-VF3_Interior_Hero.webp",
      },
      {
        title: "Đèn chiếu sáng LED thông minh",
        desc: "Hệ thống đèn full-LED tăng khả năng quan sát ban đêm và tạo dấu ấn nhận diện mạnh mẽ.",
        image: "/images/vinfast/gallery/vf3/reserves-VF3-vf3section-4.webp",
      },
      {
        title: "La-zăng hợp kim thể thao",
        desc: "Mâm xe hợp kim thiết kế đa chấu, tăng vẻ thể thao và ổn định khi vận hành.",
        image: "/images/vinfast/gallery/vf3/reserves-VF3-vf3section-4.1.webp",
      },
      {
        title: "Cảm biến hỗ trợ quan sát",
        desc: "Camera và cảm biến hỗ trợ quan sát, đỗ xe an toàn trong không gian chật hẹp.",
        image: "/images/vinfast/gallery/vf3/reserves-VF3-vf3section-5.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin VF 3 thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/gallery/vf3/reserves-VF3-vf3.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/gallery/vf3/reserves-VF3-vf3-1.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image:
          "/images/vinfast/gallery/vf3/reserves-VF3-VF3_Rear-2034_Driver_Side_Wheel_Cover1.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/gallery/vf3/exterior-181U-F1.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "VF 3 tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 210 km — công suất 40 hp",
      image: "/images/vinfast/gallery/vf3/reserves-VF3-vf3section-4.webp",
      features: [
        {
          title: "Công suất 40 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 110 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 210 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 36 phút (10% - 70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên VF 3",
      image: "/images/vinfast/gallery/vf3/reserves-VF3-vf3section-4.1.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho VF 3 — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 210,
      power: 40,
      torque: 110,
      acceleration: "19.3 giây (0-100 km/h)",
      topSpeed: 160,
      fastCharge: "36 phút (10% - 70%)",
    },
    variants: [
      {
        id: "vf-3-eco",
        name: "VF 3 Eco",
        price: 302000000,
      },
      {
        id: "vf-3-plus",
        name: "VF 3 Plus",
        price: 315000000,
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Động cơ",
            value: "01 Motor",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "30",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "110",
          },
          {
            label: "Quãng đường chạy một lần sạc đầy (km)",
            value: "215",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "36 phút (10% - 70%)",
          },
          {
            label: "Dẫn động",
            value: "RWD/Cầu sau",
          },
          {
            label: "Quãng đường (km)",
            value: "215",
          },
          {
            label: "Công suất Eco (kW)",
            value: "30",
          },
        ],
      },
    ],
  },
  vf5: {
    tagline: "Cá nhân vượt trội — Đồng hành hàng ngày",
    badges: ["Quãng đường 326 km", "Công suất 134 hp / 135 Nm"],
    slogan:
      "Xe điện VinFast VF 5 thiết kế trẻ trung, cá tính và phối màu nội ngoại thất độc đáo, trang bị những công nghệ hỗ trợ lái tiên tiến, trợ lý ảo thông minh, bảo hành 7 năm.",
    overview: {
      title: "Xe điện VinFast VF 5 thiết kế trẻ trung",
      subtitle:
        "Xe điện VinFast VF 5 thiết kế trẻ trung, cá tính và phối màu nội ngoại thất độc đáo, trang bị những công nghệ hỗ trợ lái tiên tiến, trợ lý ảo thông minh, bảo hành 7 năm.",
      bullets: [
        "Quãng đường di chuyển (chuẩn NEDC)* 326,4 km",
        "Mô men xoắn cực đại 135 Nm Thông số kỹ thuật Dài x rộng x Cao (mm) 3",
        "Công suất tối đa 134 hp",
      ],
      image: "/images/vinfast/cars/vf5.webp",
    },
    exterior: [
      {
        title: "Thiết kế ngoại thất hiện đại",
        desc: "VF 5 sở hữu ngôn ngữ thiết kế trẻ trung, khí động học tối ưu và đèn LED đặc trưng VinFast.",
        image: "/images/vinfast/gallery/vf5/VF5-2025-hero.webp",
      },
      {
        title: "Đèn chiếu sáng LED thông minh",
        desc: "Hệ thống đèn full-LED tăng khả năng quan sát ban đêm và tạo dấu ấn nhận diện mạnh mẽ.",
        image: "/images/vinfast/gallery/vf5/PDP-VF5-img-maintop.webp",
      },
      {
        title: "La-zăng hợp kim thể thao",
        desc: "Mâm xe hợp kim thiết kế đa chấu, tăng vẻ thể thao và ổn định khi vận hành.",
        image: "/images/vinfast/gallery/vf5/VF5-2025-hero-01.webp",
      },
      {
        title: "Cảm biến hỗ trợ quan sát",
        desc: "Camera và cảm biến hỗ trợ quan sát, đỗ xe an toàn trong không gian chật hẹp.",
        image: "/images/vinfast/gallery/vf5/VF5-2025-Main.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin VF 5 thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/gallery/vf5/VF5-2025-Main-1.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/gallery/vf5/VF5-2025-Main-2.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image: "/images/vinfast/gallery/vf5/VF5-2025-Main-3.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/gallery/vf5/VF5-2025-Main-4.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "VF 5 tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 326 km — công suất 134 hp",
      image: "/images/vinfast/gallery/vf5/PDP-VF5-img-maintop.webp",
      features: [
        {
          title: "Công suất 134 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 135 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 326 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 30 phút (10-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên VF 5",
      image: "/images/vinfast/gallery/vf5/VF5-2025-hero-01.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho VF 5 — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 326,
      power: 134,
      torque: 135,
      acceleration: "10.9 giây (0-100 km/h)",
      topSpeed: 160,
      fastCharge: "30 phút (10-70%)",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "3.967 x 1.723 x 1.579 ",
          },
        ],
      },
    ],
  },
  vf6: {
    tagline: "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung, hiện đại, giá",
    badges: ["Quãng đường 480 km", "Công suất 201 hp / 310 Nm"],
    slogan: "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung, hiện đại, giá",
    overview: {
      title: "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung",
      subtitle: "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung, hiện đại, giá",
      bullets: [
        "Quãng đường (NEDC)* VF 6 Eco 150 kW/201 hp Công suất tối đa VF 6 Plus 310 Nm Mô",
        "Công suất tối đa VF 6 Plus 310 Nm Mô men xoắn cực đại VF 6 Plus Nhận ưu đãi ",
      ],
      image: "/images/vinfast/cars/vf6.webp",
    },
    exterior: [
      {
        title: "Thiết kế ngoại thất hiện đại",
        desc: "VF 6 sở hữu ngôn ngữ thiết kế trẻ trung, khí động học tối ưu và đèn LED đặc trưng VinFast.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-VF6-banner.webp",
      },
      {
        title: "Đèn chiếu sáng LED thông minh",
        desc: "Hệ thống đèn full-LED tăng khả năng quan sát ban đêm và tạo dấu ấn nhận diện mạnh mẽ.",
        image: "/images/vinfast/gallery/vf6/reserves-VF6-bottom-banner.webp",
      },
      {
        title: "La-zăng hợp kim thể thao",
        desc: "Mâm xe hợp kim thiết kế đa chấu, tăng vẻ thể thao và ổn định khi vận hành.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-VF6-banner-1.webp",
      },
      {
        title: "Cảm biến hỗ trợ quan sát",
        desc: "Camera và cảm biến hỗ trợ quan sát, đỗ xe an toàn trong không gian chật hẹp.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-VF6-Lifestyle-00.webp",
      },
    ],
    interior: [
      {
        title: "Không gian nội thất rộng rãi",
        desc: "Cabin VF 6 thiết kế tối ưu, vật liệu cao cấp và ánh sáng tự nhiên cho trải nghiệm thoải mái.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-exterior-1.webp",
      },
      {
        title: "Màn hình giải trí thông minh",
        desc: "Màn hình cảm ứng trung tâm, kết nối VinFast App và điều khiển tiện ích trực quan.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-exterior-2.webp",
      },
      {
        title: "Ghế ngồi ergonomic",
        desc: "Ghế thiết kế ôm lưng, hỗ trợ thoải mái trên hành trình dài trong đô thị và cao tốc.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-exterior-3.webp",
      },
      {
        title: "Tiện nghi hàng ghế sau",
        desc: "Không gian hàng ghế sau và cốp xe linh hoạt, đáp ứng nhu cầu gia đình hàng ngày.",
        image: "/images/vinfast/gallery/vf6/reserves-VF6-interior-vf6-1.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "VF 6 tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 480 km — công suất 201 hp",
      image: "/images/vinfast/gallery/vf6/reserves-VF6-bottom-banner.webp",
      features: [
        {
          title: "Công suất 201 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 310 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 480 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 25 phút (10%-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên VF 6",
      image: "/images/vinfast/gallery/vf6/VF6-2026-VF6-banner-1.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho VF 6 — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 480,
      power: 201,
      torque: 310,
      acceleration: "8.5 giây (0-100 km/h)",
      topSpeed: 175,
      fastCharge: "25 phút (10%-70%)",
    },
    variants: [
      {
        id: "vf-6-eco",
        name: "VF 6 Eco",
        price: 689000000,
      },
      {
        id: "vf-6-plus",
        name: "VF 6 Plus",
        price: 745000000,
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "4.238 x 1.820 x 1.594",
          },
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2.730",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "150",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "310",
          },
          {
            label: "Quãng đường (NEDC) (km)",
            value: "480",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "59,6",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "25 phút (10%-70%)",
          },
          {
            label: "Dẫn động",
            value: "FWD/Cầu trước",
          },
          {
            label: "Kích thước la-zăng",
            value: "18 inch",
          },
          {
            label: "Số chỗ ngồi",
            value: "5 chỗ",
          },
        ],
      },
    ],
  },
  vf7: {
    tagline: "SUV cỡ C thể thao",
    badges: ["Quãng đường 496 km", "Công suất 349 hp / 500 Nm"],
    slogan: "Xem ưu đãi mới nhất và",
    overview: {
      title: "SUV cỡ C thời thượng và thể thao",
      subtitle: "Xem ưu đãi mới nhất và",
      bullets: [
        "Quãng đường di chuyển 1 lần sạc đầy 504 km*",
        "Hệ thống trợ lái nâng cao",
        "Mô men xoắn cực đại 500 Nm (* Thông số bản Plus tùy chọn AWD) Chi phí l",
        "Công suất tối đa 260 kW",
      ],
      image: "/images/vinfast/cars/vf7.webp",
    },
    exterior: [
      {
        title: "Ngoại thất kế thừa và đổi mới từ hơn trăm năm lịch sử của ngành ô tô.",
        desc: "Ngoại thất kế thừa và đổi mới từ hơn trăm năm lịch sử của ngành ô tô.",
        image: "/images/vinfast/gallery/vf7/reserves-VF7-vf7-hero-banner.webp",
      },
      {
        title: "Triết lý thiết kế “Vũ trụ phi đối xứng”.",
        desc: "Lấy cảm hứng từ vũ trụ và các vật thể bay trong không gian, VF 7 hiện thân cho sự tự do, công nghệ, thời đại, cá tính, mạnh mẽ và thể thao, thoả mãn mọi tâm hồn đam mê thẩm mỹ và tốc độ.",
        image: "/images/vinfast/gallery/vf7/reserves-VF7-vf7-lead-banner.webp",
      },
    ],
    interior: [
      {
        title: "Thiết kế nội thất hướng tới người lái.",
        desc: "Thiết kế nội thất hướng tới người lái.",
        image: "/images/vinfast/gallery/vf7/reserves-VF7-vf7-hero-banner.webp",
      },
      {
        title: "Tiện nghi thông minh tích hợp trên màn hình giải trí.",
        desc: "Với kích cỡ 12,9 inch, có thể tùy chỉnh cá nhân hóa theo người dùng. Màn hình giải trí cảm ứng của VF 7 có thể giúp điều khiển các chức năng trên xe bằng cách vuốt/chạm nhẹ hoặc ra lệnh cho trợ lý ảo qua giọng nói.",
        image: "/images/vinfast/gallery/vf7/reserves-VF7-vf7-lead-banner.webp",
      },
      {
        title: "Triết lý thiết kế “Vũ trụ phi đối xứng”.",
        desc: "Lấy cảm hứng từ vũ trụ và các vật thể bay trong không gian, VF 7 hiện thân cho sự tự do, công nghệ, thời đại, cá tính, mạnh mẽ và thể thao, thoả mãn mọi tâm hồn đam mê thẩm mỹ và tốc độ.",
        image: "/images/vinfast/gallery/vf7/VF7-exterior-product-CE1M.webp",
      },
      {
        title: "Kiến tạo không gian trải nghiệm phóng khoáng, tự do và tràn đầy năng lượng.",
        desc: "Tận hưởng hành trình trong không gian riêng tư và rộng rãi của chiếc xe, nơi mỗi chi tiết mang đậm dấu ấn cá nhân tạo nên cuộc phiêu lưu độc đáo của riêng bạn.",
        image: "/images/vinfast/gallery/vf7/VF7-exterior-product-CE1V.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi",
        desc: "Điều khiển bằng giọng nói tiếng Việt — điều hòa, giải trí, dẫn đường và tiện ích thông minh.",
      },
      {
        icon: "adas",
        title: "Hệ thống ADAS",
        desc: "Hỗ trợ lái nâng cao với cảnh báo va chạm, giữ làn và camera quan sát toàn cảnh.",
      },
      {
        icon: "app",
        title: "Ứng dụng VinFast",
        desc: "Theo dõi trạng thái xe, điều khiển từ xa và đặt lịch bảo dưỡng qua điện thoại.",
      },
      {
        icon: "fota",
        title: "Cập nhật FOTA",
        desc: "Nâng cấp phần mềm từ xa, luôn cập nhật tính năng mới nhất cho xe.",
      },
    ],
    technologySubtitle:
      "VF 7 tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường 496 km — công suất 349 hp",
      image: "/images/vinfast/gallery/vf7/reserves-VF7-vf7-lead-banner.webp",
      features: [
        {
          title: "Công suất 349 hp",
          desc: "Động cơ điện mạnh mẽ với mô-men xoắn 500 Nm, vận hành êm ái và phản hồi nhanh.",
        },
        {
          title: "Quãng đường 496 km",
          desc: "Pin LFP cho phép di chuyển xa trên một lần sạc đầy, phù hợp đô thị và hành trình dài.",
        },
        {
          title: "Sạc nhanh tiện lợi",
          desc: "Sạc DC 26 phút (10-70%) tại trạm V-Green hoặc sạc tại nhà qua đêm.",
        },
        {
          title: "3 chế độ lái",
          desc: "Eco, Normal và Sport — tùy chỉnh theo phong cách lái của bạn.",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên VF 7",
      image: "/images/vinfast/gallery/vf7/VF7-exterior-product-CE1M.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc cho VF 7 — trạm V-Green, sạc tại nhà và bộ sạc di động tiện lợi.",
      image: "/images/vinfast/charging/pin-oto.webp",
    },
    quickSpecs: {
      range: 496,
      power: 349,
      torque: 500,
      acceleration: "5.8 giây (0-100 km/h)",
      topSpeed: 200,
      fastCharge: "26 phút (10-70%)",
    },
    variants: [
      {
        id: "vf-7-eco",
        name: "VF 7 Eco",
        price: 789000000,
      },
      {
        id: "vf-7-plus-tt",
        name: "VF 7 Plus - TT",
        price: 949000000,
      },
      {
        id: "vf-7-plus-tk",
        name: "VF 7 Plus - TK",
        price: 969000000,
      },
      {
        id: "vf-7-plus-tt-tc2",
        name: "VF 7 Plus - TT - TC2",
        price: 889000000,
      },
      {
        id: "vf-7-plus-tk-tc2",
        name: "VF 7 Plus - TK - TC2",
        price: 909000000,
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2.840",
          },
          {
            label: "Dài x Rộng x Cao (mm)",
            value: " ",
          },
          {
            label: "Quãng đường (km)",
            value: "440",
          },
          {
            label: "Dung lượng pin (kWh)",
            value: "59,6",
          },
          {
            label: "Công suất Eco (kW)",
            value: "130",
          },
        ],
      },
    ],
  },
  vf9: {
    hideBatteryOption: true,
    variants: [
      {
        id: "vf-9-eco",
        name: "VF 9 Eco",
        price: 1499000000,
        rollingCost: 1_324_120_000,
      },
      {
        id: "vf-9-plus-tt",
        name: "VF 9 Plus - TT",
        price: 1699000000,
        rollingCost: 1_500_120_000,
      },
    ],
    safety: {
      title: "AN TOÀN VƯỢT TRỘI",
      subtitle: "Hệ thống an toàn chủ động và thụ động bảo vệ toàn diện trên VF 9",
      image: "/images/vinfast/gallery/vf9/vf9-202406-img-vf9-top-side.webp",
      features: [
        {
          title: "Camera quan sát",
          desc: "Hỗ trợ quan sát và đỗ xe an toàn trong không gian hẹp.",
        },
        {
          title: "Cảnh báo va chạm",
          desc: "Phát hiện và cảnh báo nguy cơ va chạm phía trước.",
        },
        {
          title: "Hỗ trợ giữ làn",
          desc: "Cảnh báo lệch làn và hỗ trợ giữ làn đường khi di chuyển.",
        },
        {
          title: "Khung xe vững chắc",
          desc: "Kết cấu thân vỏ chịu lực, túi khí bảo vệ hành khách toàn diện.",
        },
      ],
      highlights: ["ADAS", "Pin LFP an toàn", "ASEAN NCAP"],
    },
    badges: ["Quãng đường 626 km", "Công suất 402 hp / 620 Nm"],
    technologySubtitle:
      "VF 9 tích hợp hệ sinh thái thông minh VinFast — kết nối, an toàn và tiện nghi trên mọi hành trình.",
  },
};

export const CAR_DETAIL_PATCHES: Partial<Record<string, Partial<CarDetail>>> = {
  ...GENERATED_PATCHES,
  ...VF8_DETAIL_PATCHES,
};
