// Auto-generated by scripts/generate-vinfast-detail-overrides.mjs
// Source: VinFast brochures + https://vinfastauto.com/vn_vi
// Last synced: 2026-06-26T12:44:56.446Z

export const VINFAST_CAR_DETAIL_OVERRIDES: Partial<Record<string, Record<string, unknown>>> = {
  "vf8-all-new": {
    tagline: "VF 8 Thế Hệ Mới",
    badges: ["Công suất 170 kW / Mô-men 330 Nm", "Quãng đường 480-500 km (NEDC)"],
    slogan: "Khi phong cách trở thành dấu ấn — SUV điện cỡ D thế hệ mới",
    variants: [
      {
        id: "vf-8-all-new",
        name: "VF 8 All New",
        price: 999000000,
      },
    ],
    overview: {
      title: "Khi phong cách trở thành dấu ấn",
      subtitle:
        "VF 8 thế hệ mới định hình phong cách di chuyển Xanh hiện đại, nâng chuẩn công nghệ Việt.",
      bullets: [
        "Công suất 170 kW / Mô-men 330 Nm",
        "Quãng đường 480-500 km (NEDC)",
        "Pin 60 kWh — sạc nhanh dưới 30 phút (10%-70%)",
      ],
      image: "/images/vinfast/cars/vf8-all-new.webp",
    },
    exterior: [
      {
        title: "Trải nghiệm thị giác không giới hạn",
        desc: "Ngoại thất VF 8 gây ấn tượng với diện mạo đặc trưng của xe điện thế hệ mới, dải đèn cánh chim kéo dài đầy chiều sâu.",
        image: "/images/vinfast/cars/vf8-all-new.webp",
      },
    ],
    interior: [
      {
        title: "Nội thất khoáng đạt - Nâng tầm tiện nghi",
        desc: "Ghế ngồi VF 8 mới giúp giải tỏa áp lực, hỗ trợ tuần hoàn cơ thể trong mọi điều kiện di chuyển.",
        image: "/images/vinfast/cars/vf8-all-new.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Công suất tối đa (kW)",
            value: "170",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "330",
          },
          {
            label: "Quãng đường (NEDC) (km)",
            value: "480-500",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "60,13",
          },
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "4701 x 1872 x 1670",
          },
          {
            label: "Số ghế ngồi",
            value: "5 ghế",
          },
          {
            label: "Thời gian nạp pin nhanh nhất (10%-70%)",
            value: "Dưới 30 phút",
          },
          {
            label: "Kích thước mâm xe",
            value: "19 Inch",
          },
          {
            label: "Màn hình giải trí trung tâm",
            value: "12,9 Inch",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 480,
      power: 228,
      torque: 330,
      acceleration: "—",
      topSpeed: 175,
      fastCharge: "Dưới 30 phút (10%-70%)",
    },
  },
  "vf-mpv7": {
    tagline: "VF MPV 7",
    badges: ["Quãng đường 450 km (NEDC)", "Công suất 150 kW / Mô-men 280 Nm"],
    slogan: "Gia đình sum vầy — MPV điện 7 chỗ",
    variants: [
      {
        id: "vf-mpv-7",
        name: "VF MPV 7",
        price: 819000000,
      },
    ],
    overview: {
      title: "VF MPV 7 — Gia đình sum vầy, hành trình trọn vẹn",
      subtitle:
        "MPV điện 7 chỗ với quãng đường 450 km (NEDC), không gian rộng rãi cho cả gia đình.",
      bullets: [
        "Quãng đường 450 km (NEDC)",
        "Công suất 150 kW / Mô-men 280 Nm",
        "Sạc nhanh DC 80 kW — 30 phút (10%-70%)",
      ],
      image: "/images/vinfast/cars/vf-mpv7.webp",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "4740 x 1872 x 1734",
          },
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2840",
          },
          {
            label: "Khoảng sáng gầm xe (mm)",
            value: "185",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "150",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "280",
          },
          {
            label: "Quãng đường chạy (NEDC) (km)",
            value: "450",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "60,13",
          },
          {
            label: "Công suất sạc nhanh DC tối đa (kW)",
            value: "80",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "30 phút (10%-70%)",
          },
          {
            label: "Dẫn động",
            value: "FWD/Cầu trước",
          },
          {
            label: "Kích thước la-zăng",
            value: "Mâm hợp kim 19 inch",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 450,
      power: 201,
      torque: 280,
      acceleration: "—",
      topSpeed: 175,
      fastCharge: "30 phút (10%-70%)",
    },
  },
  "ec-van": {
    tagline: "EC VAN",
    badges: [
      "Quãng đường di chuyển (NEDC) 175 km",
      "Mô men xoắn cực đại 110 Nm Quãng đường di chuyển (NEDC) 175 km/sạc đầy",
    ],
    slogan: "Linh hoạt lưu thông nội đô, vận hành êm ái, giảm chi phí vận hành, tối đa lợi nhuận",
    variants: [
      {
        id: "ec-van-tc",
        name: "EC Van - TC",
        price: 285000000,
      },
      {
        id: "ec-van-nc",
        name: "EC Van - NC",
        price: 305000000,
      },
      {
        id: "ec-van-nc-cua-truot",
        name: "EC Van - NC cửa trượt",
        price: 325000000,
      },
    ],
    overview: {
      title: "Vận tải đa năng, tiện dụng, sinh lời",
      subtitle:
        "Linh hoạt lưu thông nội đô, vận hành êm ái, giảm chi phí vận hành, tối đa lợi nhuận",
      bullets: [
        "Quãng đường di chuyển (NEDC) 175 km",
        "Mô men xoắn cực đại 110 Nm Quãng đường di chuyển (NEDC) 175 km/sạc đầy",
        "Công suất tối đa 30 kW",
      ],
      image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-banner.webp",
    },
    exterior: [
      {
        title: "Cách mạng xanh trong vận tải hàng hóa",
        desc: "EC Van tiên phong mang đến giải pháp vận chuyển thương mại đột phá, nổi bật với khả năng vận hành linh hoạt, êm ái và tiết kiệm chi phí. Sở hữu thiết kế hiện đại, tiện dụng cùng bảng màu ngoại thất với 4 lựa chọn nổi bật Xanh – Vàng – Trắng – Đỏ, EC Van không chỉ là phương tiện di chuyển mà còn là đối tác tin cậy, phương tiện sinh kế phù hợp cho kinh tế hộ gia đình, doanh nghiệp.",
        image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-banner.webp",
      },
    ],
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường di chuyển (NEDC) 175 km",
      image: "/images/vinfast/gallery/ec-van/landingpage-ecvan-spec.webp",
      features: [
        {
          title: "Quãng đường di chuyển (NEDC)",
          desc: "Quãng đường di chuyển (NEDC) 175 km",
        },
        {
          title: "Mô men xoắn cực đại",
          desc: "Mô men xoắn cực đại 110 Nm Quãng đường di chuyển (NEDC) 175 km/sạc đầy",
        },
        {
          title: "Công suất tối đa",
          desc: "Công suất tối đa 30 kW",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "3.767 x 1.680 x 1.790 ",
          },
        ],
      },
    ],
  },
  "minio-green": {
    tagline: "MINIO GREEN",
    badges: ["Quãng đường 210 km (NEDC)", "Công suất 30 kW / Mô-men 65 Nm"],
    slogan: "Khởi nghiệp trong tầm tay — MiniCar điện đô thị gọn nhẹ",
    variants: [
      {
        id: "minio-green",
        name: "Minio Green",
        price: 269000000,
      },
    ],
    overview: {
      title: "MINIO GREEN - KHỞI NGHIỆP TRONG TẦM TAY",
      subtitle: "Sở hữu kích thước gọn, vừa vặn với mọi ngõ hẻm, từ đô thị đến nông thôn Việt Nam.",
      bullets: [
        "Quãng đường 210 km (NEDC)",
        "Công suất 30 kW / Mô-men 65 Nm",
        "Dải màu trẻ trung lên tới 14 màu",
      ],
      image: "/images/vinfast/cars/minio-green.webp",
    },
    exterior: [
      {
        title: "Ưu điểm, điểm nổi bật",
        desc: "Vận hành đơn giản, tối ưu phù hợp cho người mới sử dụng EV.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
      {
        title: "Dải màu trẻ trung",
        desc: "Minio Green chính thức là chiến thần vỏn vẹn 2 cửa với lên tới 14 tùy chọn màu sắc cá tính.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
    ],
    interior: [
      {
        title: "Chi tiết nội thất",
        desc: "Không gian đủ cho gia đình 2 người lớn, 2 trẻ em.",
        image: "/images/vinfast/cars/minio-green.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2065",
          },
          {
            label: "Khoảng sáng gầm xe (mm)",
            value: "166,3",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "30",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "65",
          },
          {
            label: "Quãng đường chạy (NEDC) (km/lần sạc đầy)",
            value: "210",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "18,3",
          },
          {
            label: "Dẫn động",
            value: "RWD/Cầu sau",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 210,
      power: 40,
      torque: 65,
      acceleration: "—",
      topSpeed: 160,
      fastCharge: "—",
    },
  },
  "herio-green": {
    tagline: "HERIO GREEN",
    badges: ["Quãng đường 326 km (NEDC)", "Công suất 100 kW / Mô-men 135 Nm"],
    slogan: "A-SUV điện — trọn vẹn trải nghiệm cùng Herio",
    variants: [
      {
        id: "herio-green",
        name: "Herio Green",
        price: 499000000,
      },
    ],
    overview: {
      title: "HERIO GREEN — A-SUV điện đô thị",
      subtitle:
        "Herio Green sở hữu thiết kế hiện đại, trẻ trung với các lựa chọn phối màu nội ngoại thất cá tính.",
      bullets: ["Quãng đường 326 km (NEDC)", "Công suất 100 kW / Mô-men 135 Nm", "Pin 37,23 kWh"],
      image: "/images/vinfast/cars/herio-green.webp",
    },
    exterior: [
      {
        title: "Thiết kế trẻ trung",
        desc: "Herio Green nổi bật với các lựa chọn phối màu nội ngoại thất, cá nhân hóa theo phong cách sống.",
        image: "/images/vinfast/cars/herio-green.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2514",
          },
          {
            label: "Khoảng sáng gầm xe (mm)",
            value: "160",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "100",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "135",
          },
          {
            label: "Quãng đường chạy (NEDC) (km)",
            value: "326",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "37,23",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 326,
      power: 134,
      torque: 135,
      acceleration: "—",
      topSpeed: 160,
      fastCharge: "—",
    },
  },
  "nerio-green": {
    tagline:
      "Đặt cọc xe điện Nerio Green, C-SUV thuần điện thiết kế hiện đại, công nghệ tiên tiến, vận hành tiết",
    badges: [
      "Quãng đường chạy (NEDC) 318,6 km",
      "Mô men xoắn cực đại 242 Nm Quãng đường chạy (NEDC) 318,6 km/lần sạc đầy",
    ],
    slogan:
      "Đặt cọc xe điện Nerio Green, C-SUV thuần điện thiết kế hiện đại, công nghệ tiên tiến, vận hành tiết kiệm và tiện lợi, bảo hành 10 năm, phù hợp với tài xế công nghệ.",
    variants: [
      {
        id: "nerio-green",
        name: "Nerio Green",
        price: 668000000,
      },
    ],
    overview: {
      title: "Đặt cọc xe điện Nerio Green",
      subtitle:
        "Đặt cọc xe điện Nerio Green, C-SUV thuần điện thiết kế hiện đại, công nghệ tiên tiến, vận hành tiết kiệm và tiện lợi, bảo hành 10 năm, phù hợp với tài xế công nghệ.",
      bullets: [
        "Quãng đường chạy (NEDC) 318,6 km",
        "Mô men xoắn cực đại 242 Nm Quãng đường chạy (NEDC) 318,6 km/lần sạc đầy",
        "Công suất tối đa 110 kW",
      ],
      image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-green.webp",
    },
    technology: [
      {
        icon: "app",
        title: "Công nghệ thông minh",
        desc: "Đặt cọc xe điện Nerio Green, C-SUV thuần điện thiết kế hiện đại, công nghệ tiên tiến, vận hành tiết kiệm và tiện lợi, bảo hành 10 năm, phù hợp với tài xế công nghệ.",
      },
    ],
    technologySubtitle:
      "Đặt cọc xe điện Nerio Green, C-SUV thuần điện thiết kế hiện đại, công nghệ tiên tiến, vận hành tiết kiệm và tiện lợi, bảo hành 10 năm, phù hợp với tài xế công nghệ.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường chạy (NEDC) 318,6 km",
      image: "/images/vinfast/gallery/nerio-green/vgreen-nerio-green-nerio-img-01-sp.webp",
      features: [
        {
          title: "Quãng đường chạy (NEDC)",
          desc: "Quãng đường chạy (NEDC) 318,6 km",
        },
        {
          title: "Mô men xoắn cực đại",
          desc: "Mô men xoắn cực đại 242 Nm Quãng đường chạy (NEDC) 318,6 km/lần sạc đầy",
        },
        {
          title: "Công suất tối đa",
          desc: "Công suất tối đa 110 kW",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "4300 x 1768 x 1615 ",
          },
        ],
      },
    ],
  },
  "limo-green": {
    tagline: "LIMO GREEN",
    badges: ["Quãng đường 450 km (NEDC)", "Công suất 150 kW"],
    slogan: "Rộng mở không gian — MPV điện 7 chỗ",
    variants: [
      {
        id: "limo-green",
        name: "Limo Green",
        price: 749000000,
      },
    ],
    overview: {
      title: "LIMO GREEN — Rộng mở không gian, kéo dài hành trình",
      subtitle: "Xe điện 7 chỗ phù hợp gia đình đông người và vận doanh vận tải đa năng.",
      bullets: ["Quãng đường 450 km (NEDC)", "Công suất 150 kW", "7 chỗ — chiều dài cơ sở 2840 mm"],
      image: "/images/vinfast/cars/limo-green.webp",
    },
    exterior: [
      {
        title: "Thiết kế tiên tiến",
        desc: "Limo Green 7 chỗ phù hợp cho nhóm bạn, gia đình đông người cùng di chuyển.",
        image: "/images/vinfast/cars/limo-green.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2840",
          },
          {
            label: "Chiều rộng (mm)",
            value: "1872",
          },
          {
            label: "Sức chứa",
            value: "7 chỗ",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "150",
          },
          {
            label: "Quãng đường chạy (NEDC) (km)",
            value: "450",
          },
          {
            label: "Khoảng sáng gầm xe (mm)",
            value: "180",
          },
          {
            label: "Kích thước la-zăng",
            value: "18 inch",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "30 phút (10%-70%)",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 450,
      power: 201,
      torque: 0,
      acceleration: "—",
      topSpeed: 175,
      fastCharge: "30 phút (10%-70%)",
    },
  },
  vf3: {
    tagline:
      "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn, linh hoạt, tối ưu quãng đường di chuyển tro",
    badges: [
      "Mô men xoắn cực đại (Nm) 110 Quãng đường chạy một lần sạc đầy (km) 215",
      "Bảo hành chính hãng",
    ],
    slogan:
      "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn, linh hoạt, tối ưu quãng đường di chuyển trong đô thị. Xem bảng giá và thông số tại đây!",
    variants: [
      {
        id: "vf-3-eco",
        name: "VF 3 Eco",
        price: 302000000,
      },
      {
        id: "vf-3-plus",
        name: "VF 3 Plus",
        price: 315000000,
      },
    ],
    overview: {
      title: "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn",
      subtitle:
        "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn, linh hoạt, tối ưu quãng đường di chuyển trong đô thị. Xem bảng giá và thông số tại đây!",
      bullets: ["Mô men xoắn cực đại (Nm) 110 Quãng đường chạy một lần sạc đầy (km) 215"],
      image: "/images/vinfast/gallery/vf3/reserves-VF3-VF3_Interior_Hero.webp",
    },
    exterior: [
      {
        title: "VinFast VF 3 - Tự do sáng tạo, toả sáng chất riêng!",
        desc: "Với dải màu ngoại thất đa dạng và độc đáo, bao gồm 7 tùy chọn màu sắc trẻ trung và thời thượng, VF 3 là sự lựa chọn hoàn hảo giúp bạn thoả sức thể hiện sự khác biệt và cá tính của riêng mình. Dù bạn là ai, hãy lựa chọn màu sắc và trang bị VF 3 theo sở thích của bạn, và cùng VinFast biến ước mơ của bạn thành hiện thực.",
        image: "/images/vinfast/gallery/vf3/exterior-181U-F1.webp",
      },
      {
        title: "La-zăng vượt trội về kích thước & phong cách.",
        desc: "VF 3 là mẫu xe hiếm hoi trong phân khúc xe sở hữu la-zăng kích thước 16 inch, không chỉ tạo điểm nhấn về thiết kế mà còn góp phần gia tăng khả năng di chuyển trên địa hình đa dạng trong đô thị. Đặc biệt, để VF 3 tăng thêm vẻ cá tính, sự sang trọng cho chiếc xe Khách hàng có thể đặt mua ốp la -zăng tại đây.",
        image: "/images/vinfast/gallery/vf3/exterior-CE1X-F1.webp",
      },
    ],
    interior: [
      {
        title: "VinFast VF 3 - Luôn đủ chỗ cho mọi người!",
        desc: "Thiết kế thông minh và không gian nội thất tối ưu hóa của VF 3 mang lại trải nghiệm di chuyển tiện lợi, đảm bảo sự thoải mái và tiện nghi cho cả 4 chỗ ngồi. Màu sắc nội thất trang nhã, trẻ trung và cá tính, cùng chất liệu thân thiện tạo ra một không gian đặc biệt, nơi chứa đựng những kỷ niệm đáng nhớ trên mọi hành trình khám phá phong cách sống của riêng bạn!",
        image: "/images/vinfast/gallery/vf3/reserves-VF3-VF3_Interior_Hero.webp",
      },
    ],
    technology: [
      {
        icon: "drive",
        title: "VinFast VF 3 - Xe nhỏ, giá trị lớn.",
        desc: "Với thiết kế tối giản, nhỏ gọn, cá tính và năng động, VinFast VF 3 sẽ luôn cùng bạn hoà nhịp với xu thế công nghệ di chuyển xanh toàn cầu, trải nghiệm giá trị trên mỗi hành trình, và tự do thể hiện ph",
      },
      {
        icon: "drive",
        title: "VF 3 không chỉ là một chiếc xe điện tiên tiến.",
        desc: "Mà còn là một tác phẩm nghệ thuật kết hợp giữa công nghệ và sự sáng tạo trong thiết kế.",
      },
    ],
    technologySubtitle:
      "Mẫu xe mini car quốc dân sành điệu với thiết kế nhỏ gọn, linh hoạt, tối ưu quãng đường di chuyển trong đô thị. Xem bảng giá và thông số tại đây!",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Mô men xoắn cực đại (Nm) 110 Quãng đường chạy một lần sạc đầy (km) 215",
      image: "/images/vinfast/gallery/vf3/reserves-VF3-vf3section-4.1.webp",
      features: [
        {
          title: "Mô men xoắn cực đại (Nm)",
          desc: "Mô men xoắn cực đại (Nm) 110 Quãng đường chạy một lần sạc đầy (km) 215",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Động cơ",
            value: "01 Motor",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "30",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "110",
          },
          {
            label: "Quãng đường chạy một lần sạc đầy (km)",
            value: "215",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "36 phút (10% - 70%)",
          },
          {
            label: "Dẫn động",
            value: "RWD/Cầu sau",
          },
          {
            label: "Quãng đường (km)",
            value: "215",
          },
          {
            label: "Công suất Eco (kW)",
            value: "30",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 215,
      power: 40,
      torque: 110,
      acceleration: "—",
      topSpeed: 160,
      fastCharge: "36 phút (10% - 70%)",
    },
    colors: [
      {
        id: "color-0",
        name: "Summer Yellow",
        hex: "#FBBF24",
        image: "/images/vinfast/colors/vf3/summer-yellow.webp",
      },
      {
        id: "color-1",
        name: "Infinity Blanc",
        hex: "#FFFFFF",
        image: "/images/vinfast/colors/vf3/infinity-blanc.webp",
      },
      {
        id: "color-2",
        name: "Zenith Grey",
        hex: "#6B7280",
        image: "/images/vinfast/colors/vf3/zenith-grey.webp",
      },
      {
        id: "color-3",
        name: "Urban Mint",
        hex: "#34D399",
        image: "/images/vinfast/colors/vf3/urban-mint.webp",
      },
      {
        id: "color-4",
        name: "Solar Ruby",
        hex: "#DC2626",
        image: "/images/vinfast/colors/vf3/solar-ruby.webp",
      },
    ],
  },
  vf5: {
    tagline: "Cá nhân vượt trội — Đồng hành hàng ngày",
    badges: [
      "Quãng đường di chuyển (chuẩn NEDC)* 326,4 km",
      "Mô men xoắn cực đại 135 Nm Thông số kỹ thuật Dài x rộng x Cao (mm) 3",
    ],
    slogan:
      "Xe điện VinFast VF 5 thiết kế trẻ trung, cá tính và phối màu nội ngoại thất độc đáo, trang bị những công nghệ hỗ trợ lái tiên tiến, trợ lý ảo thông minh, bảo hành 7 năm.",
    variants: [
      {
        id: "vf5",
        name: "VF 5",
        price: 529000000,
      },
    ],
    overview: {
      title: "Xe điện VinFast VF 5 thiết kế trẻ trung",
      subtitle:
        "Xe điện VinFast VF 5 thiết kế trẻ trung, cá tính và phối màu nội ngoại thất độc đáo, trang bị những công nghệ hỗ trợ lái tiên tiến, trợ lý ảo thông minh, bảo hành 7 năm.",
      bullets: [
        "Quãng đường di chuyển (chuẩn NEDC)* 326,4 km",
        "Mô men xoắn cực đại 135 Nm Thông số kỹ thuật Dài x rộng x Cao (mm) 3",
        "Công suất tối đa 134 hp",
      ],
      image: "/images/vinfast/gallery/vf5/VF5-2025-hero.webp",
    },
    exterior: [
      {
        title: "Ngoại thất ấn tượng",
        desc: "Phong cách trẻ trung, năng động, cá tính.",
        image: "/images/vinfast/gallery/vf5/VF5-2025-hero.webp",
      },
    ],
    interior: [
      {
        title: "Nội thất tinh tế",
        desc: "Không gian rộng rãi, phối màu sành điệu, cuốn hút với các đường viền bắt mắt.",
        image: "/images/vinfast/gallery/vf5/PDP-VF5-img-maintop.webp",
      },
    ],
    technology: [
      {
        icon: "app",
        title: "Công nghệ thông minh",
        desc: "Xe điện VinFast VF 5 thiết kế trẻ trung, cá tính và phối màu nội ngoại thất độc đáo, trang bị những công nghệ hỗ trợ lái tiên tiến, trợ lý ảo thông minh, bảo hành 7 năm.",
      },
    ],
    technologySubtitle:
      "Xe điện VinFast VF 5 thiết kế trẻ trung, cá tính và phối màu nội ngoại thất độc đáo, trang bị những công nghệ hỗ trợ lái tiên tiến, trợ lý ảo thông minh, bảo hành 7 năm.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường di chuyển (chuẩn NEDC)* 326,4 km",
      image: "/images/vinfast/gallery/vf5/VF5-2025-hero-01.webp",
      features: [
        {
          title: "Quãng đường di chuyển (chuẩn NEDC)",
          desc: "Quãng đường di chuyển (chuẩn NEDC)* 326,4 km",
        },
        {
          title: "Mô men xoắn cực đại",
          desc: "Mô men xoắn cực đại 135 Nm Thông số kỹ thuật Dài x rộng x Cao (mm) 3",
        },
        {
          title: "Công suất tối đa",
          desc: "Công suất tối đa 134 hp",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "3.967 x 1.723 x 1.579 ",
          },
        ],
      },
    ],
    colors: [
      {
        id: "color-0",
        name: "Summer Yellow",
        hex: "#FBBF24",
        image: "/images/vinfast/colors/vf5/summer-yellow.webp",
      },
      {
        id: "color-1",
        name: "Jet Black",
        hex: "#111827",
        image: "/images/vinfast/colors/vf5/jet-black.webp",
      },
      {
        id: "color-2",
        name: "Infinity Blanc",
        hex: "#FFFFFF",
        image: "/images/vinfast/colors/vf5/infinity-blanc.webp",
      },
      {
        id: "color-3",
        name: "Zenith Grey",
        hex: "#6B7280",
        image: "/images/vinfast/colors/vf5/zenith-grey.webp",
      },
      {
        id: "color-4",
        name: "Solar Ruby",
        hex: "#DC2626",
        image: "/images/vinfast/colors/vf5/solar-ruby.webp",
      },
    ],
  },
  vf6: {
    tagline:
      "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung, hiện đại, giá đặt cọc chỉ 30 triệu đồng, ưu đãi hấ",
    badges: ["Bảo hành chính hãng"],
    slogan:
      "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung, hiện đại, giá đặt cọc chỉ 30 triệu đồng, ưu đãi hấp dẫn, chính sách hậu mãi cực tốt, thiết kế tinh tế, động cơ mạnh mẽ, là lựa chọn hoàn hảo cho gia đình trẻ.",
    variants: [
      {
        id: "vf-6-eco",
        name: "VF 6 Eco",
        price: 689000000,
      },
      {
        id: "vf-6-plus",
        name: "VF 6 Plus",
        price: 745000000,
      },
    ],
    overview: {
      title: "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung",
      subtitle:
        "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung, hiện đại, giá đặt cọc chỉ 30 triệu đồng, ưu đãi hấp dẫn, chính sách hậu mãi cực tốt, thiết kế tinh tế, động cơ mạnh mẽ, là lựa chọn hoàn hảo cho gia đình trẻ.",
      bullets: [],
      image: "/images/vinfast/gallery/vf6/VF6-2026-VF6-banner.webp",
    },
    exterior: [
      {
        title: "Ngoại thất",
        desc: "Thiết kế ngoại thất được khởi tạo từ những đường nét tinh tế đến từng chi tiết cùng vẻ ngoài năng động, ấn tượng ngay từ ánh nhìn đầu tiên.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-exterior-1.webp",
      },
      {
        title: "Ngoại thất",
        desc: "Thiết kế ngoại thất được khởi tạo từ những đường nét tinh tế đến từng chi tiết cùng vẻ ngoài năng động, ấn tượng ngay từ ánh nhìn đầu tiên.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-exterior-2.webp",
      },
      {
        title: "Ngoại thất",
        desc: "Thiết kế ngoại thất được khởi tạo từ những đường nét tinh tế đến từng chi tiết cùng vẻ ngoài năng động, ấn tượng ngay từ ánh nhìn đầu tiên.",
        image: "/images/vinfast/gallery/vf6/VF6-2026-exterior-3.webp",
      },
    ],
    interior: [
      {
        title: "Nội thất",
        desc: "Thiết kế nội thất lấy cảm hứng từ ngôi nhà thứ hai của gia đình với không gian rộng rãi, thoải mái cùng hai màu nội thất và chất liệu tự nhiên, thân thiện với người dùng.",
        image: "/images/vinfast/gallery/vf6/reserves-VF6-interior-vf6-1.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Công nghệ",
        desc: "VF 6 mang đến cho người dùng cả “thế giới công nghệ” với trợ lý ảo VinFast cùng nhiều tính năng an toàn, giải trí và tiện ích đẳng cấp.",
      },
    ],
    technologySubtitle:
      "Mẫu SUV điện VinFast VF 6 với thiết kế trẻ trung, hiện đại, giá đặt cọc chỉ 30 triệu đồng, ưu đãi hấp dẫn, chính sách hậu mãi cực tốt, thiết kế tinh tế, động cơ mạnh mẽ, là lựa chọn hoàn hảo cho gia đình trẻ.",
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "4.238 x 1.820 x 1.594",
          },
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2.730",
          },
          {
            label: "Công suất tối đa (kW)",
            value: "150",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "310",
          },
          {
            label: "Quãng đường (NEDC) (km)",
            value: "480",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "59,6",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "25 phút (10%-70%)",
          },
          {
            label: "Dẫn động",
            value: "FWD/Cầu trước",
          },
          {
            label: "Kích thước la-zăng",
            value: "18 inch",
          },
          {
            label: "Số chỗ ngồi",
            value: "5 chỗ",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 480,
      power: 201,
      torque: 310,
      acceleration: "—",
      topSpeed: 175,
      fastCharge: "25 phút (10%-70%)",
    },
  },
  vf7: {
    tagline:
      "Đặt cọc xe điện VinFast VF 7 – SUV điện phong cách, công nghệ thông minh và khả năng vận hành mạnh m",
    badges: ["Quãng đường di chuyển 1 lần sạc đầy 504 km*", "Hệ thống trợ lái nâng cao"],
    slogan:
      "Đặt cọc xe điện VinFast VF 7 – SUV điện phong cách, công nghệ thông minh và khả năng vận hành mạnh mẽ. Xem ưu đãi mới nhất và đặt cọc online ngay hôm nay.",
    variants: [
      {
        id: "vf-7-eco",
        name: "VF 7 Eco",
        price: 789000000,
      },
      {
        id: "vf-7-plus-tt",
        name: "VF 7 Plus - TT",
        price: 949000000,
      },
      {
        id: "vf-7-plus-tk",
        name: "VF 7 Plus - TK",
        price: 969000000,
      },
      {
        id: "vf-7-plus-tt-tc2",
        name: "VF 7 Plus - TT - TC2",
        price: 889000000,
      },
      {
        id: "vf-7-plus-tk-tc2",
        name: "VF 7 Plus - TK - TC2",
        price: 909000000,
      },
    ],
    overview: {
      title: "Đặt cọc xe điện VinFast VF 7 – SUV điện phong cách",
      subtitle:
        "Đặt cọc xe điện VinFast VF 7 – SUV điện phong cách, công nghệ thông minh và khả năng vận hành mạnh mẽ. Xem ưu đãi mới nhất và đặt cọc online ngay hôm nay.",
      bullets: [
        "Quãng đường di chuyển 1 lần sạc đầy 504 km*",
        "Hệ thống trợ lái nâng cao",
        "Mô men xoắn cực đại 500 Nm (* Thông số bản Plus tùy chọn AWD) Chi phí l",
        "Công suất tối đa 260 kW",
      ],
      image: "/images/vinfast/gallery/vf7/reserves-VF7-vf7-hero-banner.webp",
    },
    exterior: [
      {
        title: "Triết lý thiết kế “Vũ trụ phi đối xứng”.",
        desc: "Lấy cảm hứng từ vũ trụ và các vật thể bay trong không gian, VF 7 hiện thân cho sự tự do, công nghệ, thời đại, cá tính, mạnh mẽ và thể thao, thoả mãn mọi tâm hồn đam mê thẩm mỹ và tốc độ.",
        image: "/images/vinfast/gallery/vf7/VF7-exterior-product-CE1M.webp",
      },
      {
        title: "Triết lý thiết kế “Vũ trụ phi đối xứng”.",
        desc: "Lấy cảm hứng từ vũ trụ và các vật thể bay trong không gian, VF 7 hiện thân cho sự tự do, công nghệ, thời đại, cá tính, mạnh mẽ và thể thao, thoả mãn mọi tâm hồn đam mê thẩm mỹ và tốc độ.",
        image: "/images/vinfast/gallery/vf7/VF7-exterior-product-CE1V.webp",
      },
      {
        title: "Triết lý thiết kế “Vũ trụ phi đối xứng”.",
        desc: "Lấy cảm hứng từ vũ trụ và các vật thể bay trong không gian, VF 7 hiện thân cho sự tự do, công nghệ, thời đại, cá tính, mạnh mẽ và thể thao, thoả mãn mọi tâm hồn đam mê thẩm mỹ và tốc độ.",
        image: "/images/vinfast/gallery/vf7/VF7-exterior-product-CE1W.webp",
      },
      {
        title: "Triết lý thiết kế “Vũ trụ phi đối xứng”.",
        desc: "Lấy cảm hứng từ vũ trụ và các vật thể bay trong không gian, VF 7 hiện thân cho sự tự do, công nghệ, thời đại, cá tính, mạnh mẽ và thể thao, thoả mãn mọi tâm hồn đam mê thẩm mỹ và tốc độ.",
        image: "/images/vinfast/gallery/vf7/VF7-exterior-product-CE18.webp",
      },
    ],
    interior: [
      {
        title: "Tiện nghi thông minh tích hợp trên màn hình giải trí.",
        desc: "Với kích cỡ 12,9 inch, có thể tùy chỉnh cá nhân hóa theo người dùng. Màn hình giải trí cảm ứng của VF 7 có thể giúp điều khiển các chức năng trên xe bằng cách vuốt/chạm nhẹ hoặc ra lệnh cho trợ lý ảo qua giọng nói.",
        image: "/images/vinfast/gallery/vf7/VF7-interior-vf7-noi-that-overview.webp",
      },
      {
        title: "Triết lý thiết kế “Vũ trụ phi đối xứng”.",
        desc: "Lấy cảm hứng từ vũ trụ và các vật thể bay trong không gian, VF 7 hiện thân cho sự tự do, công nghệ, thời đại, cá tính, mạnh mẽ và thể thao, thoả mãn mọi tâm hồn đam mê thẩm mỹ và tốc độ.",
        image: "/images/vinfast/gallery/vf7/VF7-interior-vf7-noi-that-compare-left.webp",
      },
      {
        title: "Kiến tạo không gian trải nghiệm phóng khoáng, tự do và tràn đầy năng lượng.",
        desc: "Tận hưởng hành trình trong không gian riêng tư và rộng rãi của chiếc xe, nơi mỗi chi tiết mang đậm dấu ấn cá nhân tạo nên cuộc phiêu lưu độc đáo của riêng bạn.",
        image: "/images/vinfast/gallery/vf7/VF7-interior-vf7-noi-that-compare-right.webp",
      },
    ],
    technology: [
      {
        icon: "drive",
        title: "VF 7 không chỉ là một chiếc xe điện tiên tiến, mà còn là một tác phẩm nghệ thuật",
        desc: "VF 7 không chỉ là một chiếc xe điện tiên tiến, mà còn là một tác phẩm nghệ thuật kết hợp giữa công nghệ và sự sáng tạo trong thiết kế.",
      },
      {
        icon: "screen",
        title: "Tiện nghi thông minh tích hợp trên màn hình giải trí.",
        desc: "Với kích cỡ 12,9 inch, có thể tùy chỉnh cá nhân hóa theo người dùng. Màn hình giải trí cảm ứng của VF 7 có thể giúp điều khiển các chức năng trên xe bằng cách vuốt/chạm nhẹ hoặc ra lệnh cho trợ lý ảo",
      },
      {
        icon: "drive",
        title: "Triết lý thiết kế “Vũ trụ phi đối xứng”.",
        desc: "Lấy cảm hứng từ vũ trụ và các vật thể bay trong không gian, VF 7 hiện thân cho sự tự do, công nghệ, thời đại, cá tính, mạnh mẽ và thể thao, thoả mãn mọi tâm hồn đam mê thẩm mỹ và tốc độ.",
      },
    ],
    technologySubtitle:
      "Đặt cọc xe điện VinFast VF 7 – SUV điện phong cách, công nghệ thông minh và khả năng vận hành mạnh mẽ. Xem ưu đãi mới nhất và đặt cọc online ngay hôm nay.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường di chuyển 1 lần sạc đầy 504 km*",
      image: "/images/vinfast/gallery/vf7/VF7-exterior-product-CE1M.webp",
      features: [
        {
          title: "Quãng đường di chuyển",
          desc: "Quãng đường di chuyển 1 lần sạc đầy 504 km*",
        },
        {
          title: "Hệ thống trợ lái nâng cao",
          desc: "Hệ thống trợ lái nâng cao",
        },
        {
          title: "Mô men xoắn cực đại",
          desc: "Mô men xoắn cực đại 500 Nm (* Thông số bản Plus tùy chọn AWD) Chi phí l",
        },
        {
          title: "Công suất tối đa",
          desc: "Công suất tối đa 260 kW",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Chiều dài cơ sở (mm)",
            value: "2.840",
          },
          {
            label: "Dài x Rộng x Cao (mm)",
            value: " ",
          },
          {
            label: "Quãng đường (km)",
            value: "440",
          },
          {
            label: "Dung lượng pin (kWh)",
            value: "59,6",
          },
          {
            label: "Công suất Eco (kW)",
            value: "130",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 440,
      power: 0,
      torque: 0,
      acceleration: "—",
      topSpeed: 160,
      fastCharge: "—",
    },
    colors: [
      {
        id: "color-0",
        name: "Jet Black",
        hex: "#111827",
        image: "/images/vinfast/colors/vf7/jet-black.webp",
      },
      {
        id: "color-1",
        name: "Infinity Blanc",
        hex: "#FFFFFF",
        image: "/images/vinfast/colors/vf7/infinity-blanc.webp",
      },
      {
        id: "color-2",
        name: "Zenith Grey",
        hex: "#6B7280",
        image: "/images/vinfast/colors/vf7/zenith-grey.webp",
      },
      {
        id: "color-3",
        name: "Urban Mint",
        hex: "#34D399",
        image: "/images/vinfast/colors/vf7/urban-mint.webp",
      },
      {
        id: "color-4",
        name: "Solar Ruby",
        hex: "#DC2626",
        image: "/images/vinfast/colors/vf7/solar-ruby.webp",
      },
      {
        id: "color-5",
        name: "Dragon Forged",
        hex: "#7F1D1D",
      },
    ],
  },
  vf8: {
    tagline:
      "Đặt cọc xe điện VinFast VF 8, mẫu xe có thiết kế tinh tế, hệ thống hỗ trợ lái nâng cao ADAS, vận hàn",
    badges: [
      "quãng đường di chuyển mỗi lần sạc đầy lên tới 471 km",
      "Công suất 350 hp --> 201 hp 402 hp",
    ],
    slogan:
      "Đặt cọc xe điện VinFast VF 8, mẫu xe có thiết kế tinh tế, hệ thống hỗ trợ lái nâng cao ADAS, vận hành vượt trội, sự lựa chọn bậc nhất phân khúc SUV 5 chỗ.",
    variants: [
      {
        id: "vf-8-eco",
        name: "VF 8 Eco",
        price: 1019000000,
      },
      {
        id: "vf-8-eco-nang-cap",
        name: "VF 8 Eco - Nâng cấp",
        price: 999000000,
      },
      {
        id: "vf-8-plus",
        name: "VF 8 Plus",
        price: 1199000000,
      },
    ],
    overview: {
      title: "Đặt cọc xe điện VinFast VF 8",
      subtitle:
        "Đặt cọc xe điện VinFast VF 8, mẫu xe có thiết kế tinh tế, hệ thống hỗ trợ lái nâng cao ADAS, vận hành vượt trội, sự lựa chọn bậc nhất phân khúc SUV 5 chỗ.",
      bullets: [
        "quãng đường di chuyển mỗi lần sạc đầy lên tới 471 km",
        "Hệ thống trợ lái nâng cao của VinFast được trang bị công nghệ và trang thiết bị hiện đại nhất, m",
        "Công suất 350 hp --> 201 hp 402 hp",
        "100 Km/h",
      ],
      image: "/images/vinfast/gallery/vf8/PDP-vf8-img-top.webp",
    },
    exterior: [
      {
        title: "Thiết kế khí động học​",
        desc: "Giảm lực cản không khí và tăng hiệu quả vận hành, đồng thời mang lại vẻ ngoài hiện đại và mạnh mẽ.",
        image: "/images/vinfast/gallery/vf8/VF8-exterior-product-CE1V.webp",
      },
      {
        title: "Gương chiếu hậu hiện đại",
        desc: "Tự động lưu vị trí theo thói quen của chủ xe, tích hợp đèn báo rẽ và cảnh báo điểm mù tăng tăng cường sự an toàn cho Khách hàng.",
        image: "/images/vinfast/gallery/vf8/VF8-exterior-product-CE1W.webp",
      },
      {
        title: "Cửa sổ trời toàn cảnh",
        desc: "Tích hợp rèm điện, điều khiển đóng mở bằng giọng nói.",
        image: "/images/vinfast/gallery/vf8/VF8-exterior-product-CE11.webp",
      },
      {
        title: "Cảm biến và camera 360 độ",
        desc: "Giúp tài xế dễ dàng quan sát và điều khiển trong không gian hẹp hay các khu vực đông đúc.",
        image: "/images/vinfast/gallery/vf8/VF8-exterior-product-CE22.webp",
      },
    ],
    interior: [
      {
        title: "Cảm biến và camera 360 độ",
        desc: "Giúp tài xế dễ dàng quan sát và điều khiển trong không gian hẹp hay các khu vực đông đúc.",
        image: "/images/vinfast/gallery/vf8/reserves-VF8-interior-img1.webp",
      },
      {
        title: "Ghế da vegan tích hợp sưởi và thông gió",
        desc: "Đảm bảo sự thoải mái tối đa cho mọi hành trình, cho cả mùa hè và mùa đông.",
        image: "/images/vinfast/gallery/vf8/reserves-VF8-interior-img2.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo ViVi 2.0",
        desc: "Trợ lý ảo ViVi 2.0 phiên bản mới nhất, ứng dụng công nghệ AI tạo sinh, mang đến khả năng tương tác, điểu khiển xe bằng giọng nói tiếng Việt hoàn toàn tự nhiên. Đồng thời, Trợ lý ảo ViVi 2.0 sẽ là một",
      },
    ],
    technologySubtitle:
      "Đặt cọc xe điện VinFast VF 8, mẫu xe có thiết kế tinh tế, hệ thống hỗ trợ lái nâng cao ADAS, vận hành vượt trội, sự lựa chọn bậc nhất phân khúc SUV 5 chỗ.",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "quãng đường di chuyển mỗi lần sạc đầy lên tới 471 km",
      image: "/images/vinfast/gallery/vf8/PDP-vf8-img-top.webp",
      features: [
        {
          title: "quãng đường di chuyển mỗi lần sạc đầy lên tới",
          desc: "quãng đường di chuyển mỗi lần sạc đầy lên tới 471 km",
        },
        {
          title: "Hệ thống trợ lái nâng cao của VinFast được trang bị công ngh",
          desc: "Hệ thống trợ lái nâng cao của VinFast được trang bị công nghệ và trang thiết bị hiện đại nhất, m",
        },
        {
          title: "Công suất",
          desc: "Công suất 350 hp --> 201 hp 402 hp",
        },
        {
          title: "100 Km/h",
          desc: "100 Km/h",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "4.750 x 1.934 x 1.667",
          },
          {
            label: "Công suất tối đa (hp)",
            value: "402",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "620",
          },
          {
            label: "Quãng đường (km)",
            value: "471",
          },
          {
            label: "Dung lượng pin khả dụng (kWh)",
            value: "88,3",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "31 phút (10%-70%)",
          },
          {
            label: "Dẫn động",
            value: "AWD/2 cầu toàn thời gian",
          },
          {
            label: "Tăng tốc 0-100 km/h",
            value: "5,5 giây",
          },
          {
            label: "Số chỗ ngồi",
            value: "5 chỗ",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 471,
      power: 402,
      torque: 620,
      acceleration: "—",
      topSpeed: 200,
      fastCharge: "31 phút (10%-70%)",
    },
    colors: [
      {
        id: "color-0",
        name: "Jet Black",
        hex: "#111827",
        image: "/images/vinfast/colors/vf8/jet-black.webp",
      },
      {
        id: "color-1",
        name: "Infinity Blanc",
        hex: "#FFFFFF",
        image: "/images/vinfast/colors/vf8/infinity-blanc.webp",
      },
      {
        id: "color-2",
        name: "Zenith Grey",
        hex: "#6B7280",
        image: "/images/vinfast/colors/vf8/zenith-grey.webp",
      },
      {
        id: "color-3",
        name: "Urban Mint",
        hex: "#34D399",
        image: "/images/vinfast/colors/vf8/urban-mint.webp",
      },
      {
        id: "color-4",
        name: "Ivy Green",
        hex: "#065F46",
      },
      {
        id: "color-5",
        name: "Desat Silver",
        hex: "#D1D5DB",
        image: "/images/vinfast/colors/vf8/desat-silver.webp",
      },
      {
        id: "color-6",
        name: "Crimson Red",
        hex: "#B91C1C",
        image: "/images/vinfast/colors/vf8/crimson-red.webp",
      },
    ],
  },
  vf9: {
    tagline: "Sự Lựa Chọn Của Người Thành Đạt, Tiên Phong",
    badges: ["Quãng đường di chuyển/lần sạc đầy 626 km*", "Vận hành mạnh mẽ 402 hp/ 620 Nm"],
    slogan:
      "VF 9 là mẫu xe SUV 7 chỗ hàng đầu của VinFast. Với kiểu dáng tinh tế, công nghệ tiên tiến nhất và sự tỉ mỉ trong từng chi tiết, VF 9 mang đến trải nghiệm đặc biệt cao cấp cho Người sở hữu.",
    variants: [
      {
        id: "vf-9-eco",
        name: "VF 9 Eco",
        price: 1499000000,
      },
      {
        id: "vf-9-plus-tt",
        name: "VF 9 Plus - TT",
        price: 1699000000,
      },
    ],
    overview: {
      title: "Mẫu eSUV cỡ lớn Hạng sang",
      subtitle:
        "VF 9 là mẫu xe SUV 7 chỗ hàng đầu của VinFast. Với kiểu dáng tinh tế, công nghệ tiên tiến nhất và sự tỉ mỉ trong từng chi tiết, VF 9 mang đến trải nghiệm đặc biệt cao cấp cho Người sở hữu.",
      bullets: [
        "Quãng đường di chuyển/lần sạc đầy 626 km*",
        "Vận hành mạnh mẽ 402 hp/ 620 Nm",
        "Bảo hành xe 200.000 km hoặc 10 năm",
      ],
      image: "/images/vinfast/gallery/vf9/vf9-202406-hero.webp",
    },
    exterior: [
      {
        title: "Mạnh mẽ, bề thế Nâng tầm thời thượng",
        desc: "Thiết kế được lấy cảm hứng từ những chiếc du thuyền hạng sang, hoà hợp với những đường nét mạnh mẽ và phóng khoáng , đem lại vẻ ngoài độc đáo và sang trọng , xứng tầm với chủ nhân tinh hoa.",
        image: "/images/vinfast/gallery/vf9/202406-exterior-CE1V.webp",
      },
      {
        title: "Mạnh mẽ, bề thế Nâng tầm thời thượng",
        desc: "Thiết kế được lấy cảm hứng từ những chiếc du thuyền hạng sang, hoà hợp với những đường nét mạnh mẽ và phóng khoáng , đem lại vẻ ngoài độc đáo và sang trọng , xứng tầm với chủ nhân tinh hoa.",
        image: "/images/vinfast/gallery/vf9/202406-exterior-CE1W.webp",
      },
      {
        title: "Mạnh mẽ, bề thế Nâng tầm thời thượng",
        desc: "Thiết kế được lấy cảm hứng từ những chiếc du thuyền hạng sang, hoà hợp với những đường nét mạnh mẽ và phóng khoáng , đem lại vẻ ngoài độc đáo và sang trọng , xứng tầm với chủ nhân tinh hoa.",
        image: "/images/vinfast/gallery/vf9/202406-exterior-CE11.webp",
      },
      {
        title: "Mạnh mẽ, bề thế Nâng tầm thời thượng",
        desc: "Thiết kế được lấy cảm hứng từ những chiếc du thuyền hạng sang, hoà hợp với những đường nét mạnh mẽ và phóng khoáng , đem lại vẻ ngoài độc đáo và sang trọng , xứng tầm với chủ nhân tinh hoa.",
        image: "/images/vinfast/gallery/vf9/202406-exterior-CE22.webp",
      },
    ],
    interior: [
      {
        title: "Bản giao hưởng của thẩm mỹ và trải nghiệm tiện nghi",
        desc: "Ngôn ngữ thiết kế tối giản mang hơi hướng tương lai phối hợp cùng loạt vật liệu cao cấp, thân thiện với môi trường, VF 9 đem lại trải nghiệm nội thất khoáng đạt, thư thái trên mọi hành trình.",
        image: "/images/vinfast/gallery/vf9/202406-interior-interior-first-sight.webp",
      },
      {
        title: "Tuỳ chọn hàng ghế cơ trưởng chỉnh điện",
        desc: "Tuỳ chọn hàng ghế cơ trưởng chỉnh điện, tích hợp tính năng làm mát, sưởi, massage, sạc không dây.",
        image: "/images/vinfast/gallery/vf9/202406-interior-int-preview-1.webp",
      },
      {
        title: "Tuỳ chọn trần kính toàn cảnh hoà hợp với thiên nhiên",
        desc: "Tuỳ chọn trần kính toàn cảnh hoà hợp với thiên nhiên, cho không gian nội thất luôn khoáng đạt.",
        image: "/images/vinfast/gallery/vf9/202406-interior-int-slide-1.webp",
      },
      {
        title: "Nút chuyển số trực quan",
        desc: "Nút chuyển số trực quan, kèm sạc không dây tích hợp trên bệ tì tay, tiện lợi và dễ dàng sử dụng.",
        image: "/images/vinfast/gallery/vf9/202406-interior-int-preview-2.webp",
      },
    ],
    technology: [
      {
        icon: "voice",
        title: "Trợ lý ảo AI hỗ trợ Tiếng Việt",
        desc: "Trợ lý ảo AI hỗ trợ tiếng Việt, điều khiển giọng nói thông minh và kết nối dịch vụ thông minh trên xe.",
      },
      {
        icon: "adas",
        title: "Trợ lái nâng cao cấp độ 2",
        desc: "Hệ thống trợ lái nâng cao cấp độ 2 với các tính năng an toàn chủ động và hỗ trợ lái thông minh.",
      },
      {
        icon: "app",
        title: "Dịch vụ thông minh",
        desc: "Hệ sinh thái kết nối và dịch vụ tiên tiến trên xe.",
      },
    ],
    technologySubtitle:
      "Hợp tác cùng những đối tác hàng đầu trên toàn cầu, VinFast áp dụng những công nghệ hiện đại với thiết kế tập trung vào con người, đem lại trải nghiệm. Trợ lý ảo cùng loạt Dịch vụ thông minh tiên tiến, đồng hành cùng bạn",
    performance: {
      title: "HIỆU SUẤT VƯỢT TRỘI",
      subtitle: "Quãng đường di chuyển/lần sạc đầy 626 km*",
      image: "/images/vinfast/gallery/vf9/vf9-202406-img-vf9-top-side.webp",
      features: [
        {
          title: "Quãng đường di chuyển/lần sạc đầy",
          desc: "Quãng đường di chuyển/lần sạc đầy 626 km*",
        },
        {
          title: "Vận hành mạnh mẽ",
          desc: "Vận hành mạnh mẽ 402 hp/ 620 Nm",
        },
      ],
      driveModes: [
        {
          name: "Eco",
          desc: "Tiết kiệm năng lượng tối đa",
        },
        {
          name: "Normal",
          desc: "Cân bằng giữa hiệu suất và tiết kiệm",
        },
        {
          name: "Sport",
          desc: "Tăng tốc mạnh mẽ, phản hồi nhanh",
        },
      ],
    },
    privileges: {
      title: "Đặc quyền",
      subtitle: "Xứng tầm tinh hoa",
      image: "/images/vinfast/gallery/vf9/vf9-202406-lead-hero-img.webp",
      highlights: [
        "Trải nghiệm VIP tại xưởng dịch vụ VinFast",
        "Tiếp cận dịch vụ sửa chữa nhanh chóng và thuận tiện",
        "Dịch vụ chăm sóc Khách hàng tận tâm, chu đáo",
        "Sạc điện miễn phí lên tới 3 năm",
      ],
      features: [
        {
          title: "Trải nghiệm VIP tại xưởng dịch vụ VinFast",
          desc: "Được tiếp đón và tư vấn bởi đội ngũ cố vấn dịch vụ, kỹ thuật viên giàu kinh nghiệm và có tay nghề cao nhất. Quý khách sẽ được ưu tiên sắp xếp lịch bảo dưỡng, sửa chữa theo thời gian và nhu cầu của bản thân. Đồng thời, xe sẽ được tiếp nhận/phục vụ và ưu tiên sửa chữa ngay bởi những kỹ thuật viên xuất sắc nhất, và được kiểm tra chất lượng bởi quản đốc trước khi giao xe.",
          image: "/images/vinfast/gallery/vf9/vf9-202406-hero.webp",
        },
        {
          title: "Tiếp cận dịch vụ sửa chữa nhanh chóng và thuận tiện",
          desc: "Miễn phí giao nhận xe tại địa điểm theo yêu cầu của quý khách (trong giờ hành chính, phạm vi 30 km từ xưởng dịch vụ VinFast gần nhất). Hỗ trợ chi phí sửa chữa cho đại lý, đảm bảo quý khách được phục vụ nhanh chóng và hiệu quả nhất.",
          image: "/images/vinfast/gallery/vf9/PDP-vf9-img-top.webp",
        },
        {
          title: "Dịch vụ chăm sóc Khách hàng tận tâm, chu đáo",
          desc: "Hotline 24/7 với nhân viên CSKH chuyên trách tiếp đón, đảm bảo mọi yêu cầu và phản hồi được giải đáp nhanh chóng, chuyên nghiệp.",
          image: "/images/vinfast/gallery/vf9/vf9-202406-img-vf9-top-side.webp",
        },
        {
          title: "Sạc điện miễn phí lên tới 3 năm",
          desc: "Theo chương trình miễn phí sạc từ V-Green, áp dụng kèm điều kiện và điều khoản. Vui lòng liên hệ đại lý để biết thông tin chi tiết.",
          image: "/images/vinfast/gallery/vf9/vf9-202406-lead-hero-img.webp",
        },
      ],
    },
    charging: {
      title: "Giải pháp Pin và Trạm sạc",
      desc: "VinFast cung cấp đa dạng giải pháp sạc để đáp ứng nhu cầu sử dụng của Khách hàng một cách thuận tiện nhất.",
      image: "/images/vinfast/gallery/vf9/202406-exterior-CE1V.webp",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "5.119 x 2.254 x 1.697",
          },
          {
            label: "Chiều dài cơ sở (mm)",
            value: "3.149",
          },
          {
            label: "Khoảng sáng gầm xe không tải (mm)",
            value: "174",
          },
          {
            label: "Công suất tối đa (hp/kW)",
            value: "402/300",
          },
          {
            label: "Mô men xoắn cực đại (Nm)",
            value: "620",
          },
          {
            label: "Tốc độ tối đa (km/h)",
            value: "200",
          },
          {
            label: "Quãng đường (km)",
            value: "626",
          },
          {
            label: "Dung lượng pin (kWh) - khả dụng",
            value: "123",
          },
          {
            label: "Loại pin",
            value: "CATL",
          },
          {
            label: "Thời gian nạp pin nhanh nhất",
            value: "35 phút (10%-70%)",
          },
          {
            label: "Dẫn động",
            value: "AWD/2 cầu toàn thời gian",
          },
          {
            label: "Trọng lượng không tải (kg)",
            value: "2.911",
          },
          {
            label: "Dung tích cốp gập ghế (L)",
            value: "926",
          },
          {
            label: "Số chỗ ngồi",
            value: "7 chỗ",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 626,
      power: 402,
      torque: 620,
      acceleration: "—",
      topSpeed: 200,
      fastCharge: "35 phút (10%-70%)",
    },
    colors: [
      {
        id: "color-0",
        name: "Jet Black",
        hex: "#111827",
        image: "/images/vinfast/colors/vf9/jet-black.webp",
      },
      {
        id: "color-1",
        name: "Infinity Blanc",
        hex: "#FFFFFF",
        image: "/images/vinfast/colors/vf9/infinity-blanc.webp",
      },
      {
        id: "color-2",
        name: "Zenith Grey",
        hex: "#6B7280",
        image: "/images/vinfast/colors/vf9/zenith-grey.webp",
      },
      {
        id: "color-3",
        name: "Urban Mint",
        hex: "#34D399",
        image: "/images/vinfast/colors/vf9/urban-mint.webp",
      },
      {
        id: "color-4",
        name: "Ivy Green",
        hex: "#065F46",
        image: "/images/vinfast/colors/vf9/ivy-green.webp",
      },
      {
        id: "color-5",
        name: "Desat Silver",
        hex: "#D1D5DB",
        image: "/images/vinfast/colors/vf9/desat-silver.webp",
      },
      {
        id: "color-6",
        name: "Crimson Red",
        hex: "#B91C1C",
        image: "/images/vinfast/colors/vf9/crimson-red.webp",
      },
    ],
  },
};

export const VINFAST_SCOOTER_DETAIL_OVERRIDES: Partial<Record<string, Record<string, unknown>>> = {
  "flazz-max": {
    tagline: "FLAZZ MAX",
    badges: ["Tốc độ tối đa 49 km/h", "Quãng đường ~87 km/lần sạc"],
    slogan: "Độc đáo — bật chất thể thao",
    variants: [
      {
        id: "flazz-max-khong-kem-pin",
        name: "Flazz Max (không kèm pin)",
        price: 14990000,
      },
      {
        id: "flazz-max-kem-pin",
        name: "Flazz Max (kèm pin)",
        price: 20600000,
      },
    ],
    overview: {
      title: "ĐỘC ĐÁO - BẬT CHẤT THỂ THAO",
      subtitle:
        "Flazz Max sở hữu công suất tối đa 1500W, pin LFP 1.5kWh, thiết kế thể thao năng động.",
      bullets: ["Tốc độ tối đa 49 km/h", "Quãng đường ~87 km/lần sạc", "Công suất tối đa 1500 W"],
      image: "/images/vinfast/scooters/flazz-max.webp",
    },
    exterior: [
      {
        title: "KIỂU DÁNG",
        desc: "Thiết kế mạnh mẽ, trẻ trung với các đường nét góc cạnh, đậm chất phố.",
        image: "/images/vinfast/scooters/flazz-max.webp",
      },
      {
        title: "BỀN BỈ & AN TOÀN",
        desc: "Động cơ đạt tiêu chuẩn chống nước IP67, an tâm di chuyển trong điều kiện mưa.",
        image: "/images/vinfast/scooters/flazz-max.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Tốc độ tối đa (km/h)",
            value: "49",
          },
          {
            label: "Quãng đường 1 lần sạc (km)",
            value: "~87",
          },
          {
            label: "Công suất tối đa (W)",
            value: "1500",
          },
          {
            label: "Công suất danh định (W)",
            value: "1000",
          },
          {
            label: "Dung lượng pin (kWh)",
            value: "1,5",
          },
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "1745 x 700 x 1050",
          },
          {
            label: "Thể tích cốp (L)",
            value: "4",
          },
          {
            label: "Thời gian sạc tiêu chuẩn",
            value: "Khoảng 8h (0%-100%)",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 87,
      topSpeed: 49,
      motorPower: 1500,
      trunk: 4,
      chargingTime: "Khoảng 8h",
      weight: 0,
    },
  },
  "amio-s": {
    tagline: "AMIO S",
    badges: ["Tốc độ tối đa 25 km/h", "Quãng đường ~65 km/lần sạc"],
    slogan: "Xe điện đô thị tiện lợi",
    variants: [
      {
        id: "amio-s",
        name: "AMIO S",
        price: 13900000,
      },
    ],
    overview: {
      title: "AMIO S",
      subtitle: "Xe máy điện đô thị gọn nhẹ, tốc độ tối đa 25 km/h.",
      bullets: ["Tốc độ tối đa 25 km/h", "Quãng đường ~65 km/lần sạc", "Công suất 800 W"],
      image: "/images/vinfast/scooters/amio-s.webp",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Tốc độ tối đa (km/h)",
            value: "25",
          },
          {
            label: "Quãng đường 1 lần sạc (km)",
            value: "~65",
          },
          {
            label: "Công suất tối đa (W)",
            value: "800",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 65,
      topSpeed: 25,
      motorPower: 800,
      trunk: 0,
      chargingTime: "—",
      weight: 0,
    },
  },
  "evo-lite": {
    tagline: "EVO LITE",
    badges: ["Tốc độ tối đa 49 km/h", "Quãng đường ~165 km/lần sạc"],
    slogan: "Sống xanh, đi chất — quãng đường lên tới ~165 km/lần sạc",
    variants: [
      {
        id: "evo-lite",
        name: "EVO Lite",
        price: 17000000,
      },
    ],
    overview: {
      title: "Xe máy điện VinFast Evo Lite",
      subtitle: "Hệ thống đèn Full LED và đèn pha LED Projector.",
      bullets: [
        "Hệ thống đèn Full LED và đèn pha LED Projector.",
        "Thể tích cốp 12L (khi lắp 2 pin) tối ưu sức chứa - tối đa nhu cầu.",
        "Sàn để chân rộng thoáng cho tư thế ngồi thoải mái.",
        "Hệ thống giảm xóc với giảm chấn thủy lực, hỗ trợ xe di chuyển êm ái trên nhiều địa hình.",
      ],
      image: "/images/vinfast/scooters/evo-lite.webp",
    },
    exterior: [
      {
        title: "Hệ thống đèn Full LED và đèn pha LED Projector",
        desc: "Hệ thống đèn Full LED và đèn pha LED Projector.",
        image: "/images/vinfast/scooters/evo-lite.webp",
      },
      {
        title: "Thể tích cốp Evo Lite",
        desc: "Thể tích cốp 12L (khi lắp 2 pin) tối ưu sức chứa - tối đa nhu cầu.",
        image: "/images/vinfast/scooters/evo-lite.webp",
      },
      {
        title: "Sàn để chân Evo Lite",
        desc: "Sàn để chân rộng thoáng cho tư thế ngồi thoải mái.",
        image: "/images/vinfast/scooters/evo-lite.webp",
      },
      {
        title: "Hệ thống giảm xóc Evo Lite",
        desc: "Hệ thống giảm xóc với giảm chấn thủy lực, hỗ trợ xe di chuyển êm ái trên nhiều địa hình.",
        image: "/images/vinfast/scooters/evo-lite.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Tốc độ tối đa (km/h)",
            value: "49",
          },
          {
            label: "Quãng đường 1 lần sạc (km)",
            value: "~165",
          },
          {
            label: "Công suất tối đa (W)",
            value: "2300",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 165,
      topSpeed: 49,
      motorPower: 2300,
      trunk: 0,
      chargingTime: "—",
      weight: 0,
    },
  },
  amio: {
    tagline: "AMIO",
    badges: ["Tốc độ tối đa 30 km/h", "Quãng đường ~65 km/lần sạc"],
    slogan: "Di chuyển xanh mỗi ngày",
    variants: [
      {
        id: "amio",
        name: "Amio",
        price: 13900000,
      },
    ],
    overview: {
      title: "AMIO",
      subtitle: "Xe máy điện đô thị với tốc độ tối đa 30 km/h.",
      bullets: ["Tốc độ tối đa 30 km/h", "Quãng đường ~65 km/lần sạc", "Công suất 800 W"],
      image: "/images/vinfast/scooters/amio.webp",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Tốc độ tối đa (km/h)",
            value: "30",
          },
          {
            label: "Quãng đường 1 lần sạc (km)",
            value: "~65",
          },
          {
            label: "Công suất tối đa (W)",
            value: "800",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 65,
      topSpeed: 30,
      motorPower: 800,
      trunk: 0,
      chargingTime: "—",
      weight: 0,
    },
  },
  viper: {
    tagline: "VIPER",
    badges: ["Tốc độ tối đa 70 km/h", "Quãng đường ~156 km/lần sạc"],
    slogan: "Bản lĩnh tiên phong — động cơ BLDC Inhub 3000W, pin LFP 1.5 kWh",
    variants: [
      {
        id: "viper",
        name: "Viper",
        price: 39900000,
      },
    ],
    overview: {
      title: "Xe máy điện VinFast Viper",
      subtitle: "Bản lĩnh tiên phong — động cơ BLDC Inhub 3000W, pin LFP 1.5 kWh",
      bullets: [
        "Tốc độ tối đa 70 km/h",
        "Quãng đường ~156 km/lần sạc",
        "Công suất tối đa 3000 W",
        "Khóa thông minh Smart Key",
      ],
      image: "/images/vinfast/scooters/viper.webp",
    },
    exterior: [
      {
        title: "LINH HOẠT NÂNG CẤP 02 PIN",
        desc: "Trang bị 2 khay chứa pin trong cốp xe, giúp tối ưu không gian và dễ dàng tháo lắp.",
        image: "/images/vinfast/scooters/viper.webp",
      },
      {
        title: "HIỆU SUẤT ẤN TƯỢNG",
        desc: "VinFast Viper được trang bị động cơ BLDC Inhub với công suất tối đa 3000 W. Pin LFP có dung lượng 1.5 kWh cho khả năng vận hành mạnh mẽ, bền bỉ.",
        image: "/images/vinfast/scooters/viper.webp",
      },
      {
        title: "Màn hình TFT hiện đại",
        desc: "Màn hình TFT hiện đại, đem tới độ phân giải và tương phản cao, giúp hiển thị thông số rõ ràng, sống động.",
        image: "/images/vinfast/scooters/viper.webp",
      },
      {
        title: "Cốp xe rộng rãi",
        desc: "Cốp xe rộng rãi, tối ưu không gian chứa pin và các vật dụng cần thiết.",
        image: "/images/vinfast/scooters/viper.webp",
      },
    ],
    design: [
      {
        title: "Sàn để chân rộng rãi",
        desc: "Sàn để chân rộng rãi và vị trí để chân sau tách rời, giúp tư thế ngồi thư thái và thoải mái.",
        image: "/images/vinfast/scooters/viper.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Tốc độ tối đa (km/h)",
            value: "70",
          },
          {
            label: "Quãng đường 1 lần sạc (km)",
            value: "~156",
          },
          {
            label: "Công suất tối đa (W)",
            value: "3000",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 156,
      topSpeed: 70,
      motorPower: 3000,
      trunk: 0,
      chargingTime: "—",
      weight: 0,
    },
  },
  "feliz-ii": {
    tagline: "FELIZ II",
    badges: ["Tốc độ tối đa 70 km/h", "Quãng đường ~156 km/lần sạc"],
    slogan: "Phong cách — tiện nghi",
    variants: [
      {
        id: "feliz-ii",
        name: "Feliz II",
        price: 24900000,
      },
    ],
    overview: {
      title: "FELIZ II",
      subtitle: "Xe máy điện phong cách với quãng đường ~156 km.",
      bullets: ["Tốc độ tối đa 70 km/h", "Quãng đường ~156 km/lần sạc", "Công suất 3000 W"],
      image: "/images/vinfast/scooters/feliz-ii.webp",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Tốc độ tối đa (km/h)",
            value: "70",
          },
          {
            label: "Quãng đường 1 lần sạc (km)",
            value: "~156",
          },
          {
            label: "Công suất tối đa (W)",
            value: "3000",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 156,
      topSpeed: 70,
      motorPower: 3000,
      trunk: 0,
      chargingTime: "—",
      weight: 0,
    },
  },
  evo: {
    tagline: "EVO",
    badges: ["Tốc độ tối đa 70 km/h", "Quãng đường ~165 km (2 pin)"],
    slogan: "Đa dụng — bền bỉ",
    variants: [
      {
        id: "evo",
        name: "EVO",
        price: 19990000,
      },
    ],
    overview: {
      title: "EVO",
      subtitle: "Xe máy điện đa dụng với quãng đường ~165 km (2 pin).",
      bullets: ["Tốc độ tối đa 70 km/h", "Quãng đường ~165 km (2 pin)", "Cốp xe 12 lít"],
      image: "/images/vinfast/scooters/evo.webp",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Tốc độ tối đa (km/h)",
            value: "70",
          },
          {
            label: "Quãng đường 1 lần sạc (km)",
            value: "~165",
          },
          {
            label: "Cốp xe (lít)",
            value: "12",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 165,
      topSpeed: 70,
      motorPower: 0,
      trunk: 12,
      chargingTime: "—",
      weight: 0,
    },
  },
  zgoo: {
    tagline: "Xe Máy Điện Zgoo - Thông số, giá bán mới nhất",
    badges: [
      "Công suất/Dung lượng 1,2 kW",
      "Tốc độ tối đa 70 km/1 lần sạc Quãng đường di chuyển 1",
    ],
    slogan:
      "Xe máy điện VinFast ZGoo - Lựa chọn lý tưởng cho học sinh, không yêu cầu bằng lái. Xe sở hữu thiết kế hiện đại, động cơ ưu việt, pin LFP vượt trội. Khám phá ngay!",
    variants: [
      {
        id: "zgoo",
        name: "zgoo",
        price: 15900000,
      },
    ],
    overview: {
      title: "Xe máy điện VinFast ZGoo - Lựa chọn lý tưởng cho học sinh",
      subtitle:
        "Xe máy điện VinFast ZGoo - Lựa chọn lý tưởng cho học sinh, không yêu cầu bằng lái. Xe sở hữu thiết kế hiện đại, động cơ ưu việt, pin LFP vượt trội. Khám phá ngay!",
      bullets: [
        "Công suất/Dung lượng 1,2 kW",
        "Tốc độ tối đa 70 km/1 lần sạc Quãng đường di chuyển 1",
        "39 km/h",
      ],
      image: "/images/vinfast/scooters/zgoo.webp",
    },
    exterior: [
      {
        title: "CHẾ ĐỘ LÁI LINH HOẠT",
        desc: "Tích hợp hai chế độ lái: Eco - Êm ái và Sport - Mạnh mẽ giúp bạn di chuyển thuận tiện trong mọi hành trình.",
        image: "/images/vinfast/scooters/zgoo.webp",
      },
      {
        title: "HỆ THỐNG GIẢM XÓC MƯỢT MÀ",
        desc: "Hệ thống giảm chấm thủy lực giúp xe di chuyển ổn định trên mọi địa hình, từ đường phố đông đúc đến những cung đường gồ ghề.",
        image: "/images/vinfast/scooters/zgoo.webp",
      },
      {
        title: "ĐỘNG CƠ ƯU VIỆT",
        desc: "Động cơ Inhub với công suất 1100W giúp xe vận hành mượt mà, linh hoạt. Pin LFP đặt dưới sàn giúp xe vận hành cân bằng và ổn định ngay cả khi tăng tốc nhanh.",
        image: "/images/vinfast/scooters/zgoo.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Quãng đường (km)",
            value: "70",
          },
          {
            label: "Tốc độ tối đa (km/h)",
            value: "39",
          },
          {
            label: "Công suất động cơ (W)",
            value: "1500",
          },
          {
            label: "Loại pin",
            value: "LFP",
          },
          {
            label: "Thời gian sạc",
            value: "5 giờ (0-100%)",
          },
          {
            label: "Trọng lượng (kg)",
            value: "90",
          },
          {
            label: "Dung tích cốp (lít)",
            value: "14",
          },
          {
            label: "Kích thước (mm)",
            value: "1.700 x 680 x 1.100",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 70,
      topSpeed: 39,
      motorPower: 1500,
      trunk: 14,
      chargingTime: "5 giờ (0-100%)",
      weight: 90,
    },
  },
  flazz: {
    tagline: "Xe Máy Điện Flazz - Thông số, giá bán mới nhất",
    badges: ["Quãng đường di chuyển lên tới 135 km", "Công suất/Dung lượng 1,2 kW"],
    slogan:
      "Xe máy điện VinFast Flazz - Lựa chọn lý tưởng cho học sinh, không yêu cầu bằng lái. Xe sở hữu thiết kế cá tính, mạnh mẽ, động cơ ưu việt, pin LFP vượt trội. Khám phá ngay!",
    variants: [
      {
        id: "flazz",
        name: "Flazz",
        price: 16900000,
      },
    ],
    overview: {
      title: "Xe máy điện VinFast Flazz - Lựa chọn lý tưởng cho học sinh",
      subtitle:
        "Xe máy điện VinFast Flazz - Lựa chọn lý tưởng cho học sinh, không yêu cầu bằng lái. Xe sở hữu thiết kế cá tính, mạnh mẽ, động cơ ưu việt, pin LFP vượt trội. Khám phá ngay!",
      bullets: [
        "Quãng đường di chuyển lên tới 135 km",
        "Công suất/Dung lượng 1,2 kW",
        "Tốc độ tối đa ~135 km/1 lần sạc Quãng đường di chuyển",
        "39 km/h",
      ],
      image: "/images/vinfast/scooters/flazz.webp",
    },
    exterior: [
      {
        title: "LINH HOẠT NÂNG CẤP 02 PIN",
        desc: "Hệ thống 02 pin LFP tiên tiến với 01 pin cố định dưới sàn xe và 01 pin tháo rời đặt trong cốp.",
        image: "/images/vinfast/scooters/flazz.webp",
      },
      {
        title: "LỰA CHỌN LÝ TƯỞNG CHO ĐÔ THỊ",
        desc: "Quãng đường di chuyển lên tới 135 km. Tốc độ tối đa 39km/h, vô cùng thích hợp với điều kiện giao thông nội đô.*",
        image: "/images/vinfast/scooters/flazz.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Quãng đường (km)",
            value: "135",
          },
          {
            label: "Tốc độ tối đa (km/h)",
            value: "39",
          },
          {
            label: "Công suất động cơ (W)",
            value: "1500",
          },
          {
            label: "Loại pin",
            value: "LFP",
          },
          {
            label: "Thời gian sạc",
            value: "5 giờ (0-100%)",
          },
          {
            label: "Trọng lượng (kg)",
            value: "92",
          },
          {
            label: "Dung tích cốp (lít)",
            value: "14",
          },
          {
            label: "Kích thước (mm)",
            value: "1.720 x 680 x 1.080",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 135,
      topSpeed: 39,
      motorPower: 1500,
      trunk: 14,
      chargingTime: "5 giờ (0-100%)",
      weight: 92,
    },
  },
  "vero-x": {
    tagline: "XE MÁY ĐIỆN 02 PIN",
    badges: [
      "quãng đường di chuyển đạt tới 262 km",
      "Tốc độ tối đa ~262 km/1 lần sạc Quãng đường di chuyển",
    ],
    slogan:
      "Xe máy điện VinFast Vero X: Lái êm ái, kiểu dáng thời thượng. Cốp 35L và sàn rộng rãi, tối ưu công năng, tối đa nhu cầu. Khám phá ngay!",
    variants: [
      {
        id: "vero-x",
        name: "Vero X",
        price: 34900000,
      },
    ],
    overview: {
      title: "Xe máy điện VinFast Vero X: Lái êm ái",
      subtitle:
        "Xe máy điện VinFast Vero X: Lái êm ái, kiểu dáng thời thượng. Cốp 35L và sàn rộng rãi, tối ưu công năng, tối đa nhu cầu. Khám phá ngay!",
      bullets: [
        "quãng đường di chuyển đạt tới 262 km",
        "Tốc độ tối đa ~262 km/1 lần sạc Quãng đường di chuyển",
        "70 km/h",
      ],
      image: "/images/vinfast/scooters/vero-x.webp",
    },
    exterior: [
      {
        title: "LINH HOẠT NÂNG CẤP 02 PIN",
        desc: "Hệ thống 02 pin LFP tiên tiến với 01 pin cố định dưới sàn xe và 01 pin tháo rời đặt trong cốp.",
        image: "/images/vinfast/scooters/vero-x.webp",
      },
      {
        title: "QUÃNG ĐƯỜNG DI CHUYỂN ĐẦY ẤN TƯỢNG",
        desc: "Khẳng định ưu thế với quãng đường di chuyển đạt tới 262 km/lần sạc. Tốc độ tối đa 70 km/h, vận hành mãnh mẽ và tăng tốc từ 0 - 50 km/h chỉ trong 15 giây.",
        image: "/images/vinfast/scooters/vero-x.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "1858 x 690 x 1100 ",
          },
        ],
      },
    ],
  },
  "feliz-2025": {
    tagline: "XE MÁY ĐIỆN 02 PIN",
    badges: [
      "QUÃNG ĐƯỜNG Chinh phục quãng đường lên tới khoảng 262 km",
      "Tốc độ tối đa ~262 km/1 lần sạc Quãng đường di chuyển",
    ],
    slogan:
      "Xe máy điện Feliz 2025 thiết kế thanh lịch, nâng cấp 2 pin LFP linh hoạt, cho quãng đường lên đến ~262km/lần sạc (*)Tích hợp cốp 34L siêu rộng. Đặt cọc Feliz 2025 ngay!",
    variants: [
      {
        id: "feliz-2025",
        name: "Feliz 2025",
        price: 27900000,
      },
    ],
    overview: {
      title: "Xe máy điện Feliz 2025 thiết kế thanh lịch",
      subtitle:
        "Xe máy điện Feliz 2025 thiết kế thanh lịch, nâng cấp 2 pin LFP linh hoạt, cho quãng đường lên đến ~262km/lần sạc (*)Tích hợp cốp 34L siêu rộng. Đặt cọc Feliz 2025 ngay!",
      bullets: [
        "QUÃNG ĐƯỜNG Chinh phục quãng đường lên tới khoảng 262 km",
        "Tốc độ tối đa ~262 km/1 lần sạc Quãng đường di chuyển",
        "70 km/h",
      ],
      image: "/images/vinfast/scooters/feliz-2025.webp",
    },
    exterior: [
      {
        title: "LINH HOẠT NÂNG CẤP 02 PIN",
        desc: "Hệ thống 02 pin LFP tiên tiến với 01 pin cố định dưới sàn xe và 01 pin tháo rời đặt trong cốp.",
        image: "/images/vinfast/scooters/feliz-2025.webp",
      },
      {
        title: "QUÃNG ĐƯỜNG DI CHUYỂN ĐẦY ẤN TƯỢNG",
        desc: "Khẳng định ưu thế với quãng đường di chuyển đạt tới 262 km/lần sạc. Tốc độ tối đa 70 km/h, vận hành mạnh mẽ và tăng tốc từ 0 - 50 km/h chỉ trong vòng 16 giây.",
        image: "/images/vinfast/scooters/feliz-2025.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Dài x Rộng x Cao (mm)",
            value: "1920 x 694 x 1140 ",
          },
        ],
      },
    ],
  },
  "evo-grand": {
    tagline: "Xe Máy Điện Evo Grand - Thông số, giá bán mới nhất",
    badges: [
      "Quãng đường đi được 1 lần sạc* Khoảng 134 km (+128 Km",
      "Tốc độ tối đa 262 km/1 lần sạc* Quãng đường di chuyển",
    ],
    slogan:
      "Xe máy điện Evo Grand linh hoạt nâng cấp Pin LFP, khả năng di chuyển ấn tượng với quãng đường lên tới 262km, tốc độ 70km/h/ lần sạc. Khám phá ưu đãi mới nhất!",
    variants: [
      {
        id: "evo-grand",
        name: "Evo Grand",
        price: 23900000,
      },
    ],
    overview: {
      title: "Xe máy điện Evo Grand linh hoạt nâng cấp Pin LFP",
      subtitle:
        "Xe máy điện Evo Grand linh hoạt nâng cấp Pin LFP, khả năng di chuyển ấn tượng với quãng đường lên tới 262km, tốc độ 70km/h/ lần sạc. Khám phá ưu đãi mới nhất!",
      bullets: [
        "Quãng đường đi được 1 lần sạc* Khoảng 134 km (+128 Km",
        "Tốc độ tối đa 262 km/1 lần sạc* Quãng đường di chuyển",
        "70 km/h",
      ],
      image: "/images/vinfast/scooters/evo-grand.webp",
    },
    exterior: [
      {
        title: "Thể tích cốp 35L tối ưu sức chứa",
        desc: "Thể tích cốp 35L tối ưu sức chứa – tối đa nhu cầu.",
        image: "/images/vinfast/scooters/evo-grand.webp",
      },
      {
        title: "Linh hoạt nâng cấp 02 pin kép",
        desc: "Linh hoạt nâng cấp 02 pin kép, gấp đôi năng lượng, nâng tầm hiệu suất.",
        image: "/images/vinfast/scooters/evo-grand.webp",
      },
      {
        title: "Trải nghiệm hành trình di chuyển lên tới 262km trong một lần",
        desc: "Trải nghiệm hành trình di chuyển lên tới 262km trong một lần sạc*.",
        image: "/images/vinfast/scooters/evo-grand.webp",
      },
      {
        title: "Hệ thống đèn chiếu sáng và đèn tín hiệu Full LED cho khả năn",
        desc: "Hệ thống đèn chiếu sáng và đèn tín hiệu Full LED cho khả năng chiếu sáng mạnh mẽ, tăng khả năng quan sát.",
        image: "/images/vinfast/scooters/evo-grand.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Quãng đường (km)",
            value: "262",
          },
          {
            label: "Tốc độ tối đa (km/h)",
            value: "70",
          },
          {
            label: "Công suất động cơ (W)",
            value: "2800",
          },
          {
            label: "Loại pin",
            value: "LFP",
          },
          {
            label: "Thời gian sạc",
            value: "6 giờ (0-100%)",
          },
          {
            label: "Trọng lượng (kg)",
            value: "115",
          },
          {
            label: "Dung tích cốp (lít)",
            value: "35",
          },
          {
            label: "Kích thước (mm)",
            value: "1.920 x 700 x 1.140",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 262,
      topSpeed: 70,
      motorPower: 2800,
      trunk: 35,
      chargingTime: "6 giờ (0-100%)",
      weight: 115,
    },
  },
  "evo-grand-lite": {
    tagline: "Xe Máy Điện Evo Grand Lite - Thông số, giá bán mới nhất",
    badges: ["Tốc độ tối đa 48 km/h", "Quãng đường 198 km (2 pin)"],
    slogan: "Tiết kiệm — dễ sử dụng",
    variants: [
      {
        id: "evo-grand-lite",
        name: "Evo Grand Lite",
        price: 19900000,
      },
    ],
    overview: {
      title: "VinFast Evo Grand Lite - Xe máy điện dành cho học sinh",
      subtitle:
        "VinFast Evo Grand Lite - Xe máy điện dành cho học sinh, không yêu cầu bằng lái, vận hành êm ái, bền bỉ với công nghệ Pin LFP vượt trội. Khám phá thiết kế, tính năng và ưu đãi mới nhất!",
      bullets: [
        "Quãng đường đi được 1 lần sạc* Khoảng 70 km (+128 Km",
        "Tốc độ tối đa 198 km/1 lần sạc* Quãng đường di chuyển",
        "48 km/h",
      ],
      image: "/images/vinfast/scooters/evo-grand-lite.webp",
    },
    exterior: [
      {
        title: "Thể tích cốp 35L tối ưu sức chứa",
        desc: "Thể tích cốp 35L tối ưu sức chứa – tối đa nhu cầu.",
        image: "/images/vinfast/scooters/evo-grand-lite.webp",
      },
      {
        title: "Linh hoạt nâng cấp 02 pin kép",
        desc: "Linh hoạt nâng cấp 02 pin kép, gấp đôi năng lượng, nâng tầm hiệu suất.",
        image: "/images/vinfast/scooters/evo-grand-lite.webp",
      },
      {
        title: "Trải nghiệm hành trình di chuyển lên tới 198km trong một lần",
        desc: "Trải nghiệm hành trình di chuyển lên tới 198km trong một lần sạc*.",
        image: "/images/vinfast/scooters/evo-grand-lite.webp",
      },
      {
        title: "Hệ thống đèn chiếu sáng và đèn tín hiệu Full LED cho khả năn",
        desc: "Hệ thống đèn chiếu sáng và đèn tín hiệu Full LED cho khả năng chiếu sáng mạnh mẽ, tăng khả năng quan sát.",
        image: "/images/vinfast/scooters/evo-grand-lite.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Tốc độ tối đa (km/h)",
            value: "48",
          },
          {
            label: "Quãng đường 1 lần sạc (km)",
            value: "198",
          },
          {
            label: "Thể tích cốp (L)",
            value: "35",
          },
          {
            label: "Công suất động cơ (W)",
            value: "2500",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 198,
      topSpeed: 48,
      motorPower: 2500,
      trunk: 35,
      chargingTime: "—",
      weight: 0,
    },
  },
  drgnfly: {
    tagline: "Xe đạp điện VF DrgnFly",
    badges: ["Quãng đường di chuyển lên tới 110 km", "Bảo hành chính hãng"],
    slogan: "Xe đạp điện VF DrgnFly",
    variants: [
      {
        id: "drgnfly",
        name: "DrgnFly",
        price: 18690000,
      },
    ],
    overview: {
      title: "Xe đạp điện VF DrgnFly",
      subtitle: "Xe đạp điện VF DrgnFly",
      bullets: ["Quãng đường di chuyển lên tới 110 km"],
      image: "/images/vinfast/scooters/drgnfly.webp",
    },
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Quãng đường (km)",
            value: "110",
          },
          {
            label: "Tốc độ tối đa (km/h)",
            value: "49",
          },
          {
            label: "Công suất động cơ (W)",
            value: "250",
          },
          {
            label: "Loại pin",
            value: "Lithium-ion",
          },
          {
            label: "Thời gian sạc",
            value: "5 giờ (0-100%)",
          },
          {
            label: "Trọng lượng xe (kg)",
            value: "28",
          },
          {
            label: "Kích thước (mm)",
            value: "1.750 x 600 x 1.100",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 110,
      topSpeed: 49,
      motorPower: 250,
      trunk: 0,
      chargingTime: "5 giờ (0-100%)",
      weight: 28,
    },
  },
  "evo-lite-neo": {
    tagline: "Lựa chọn chuẩn Gen Z",
    badges: [
      "Quãng đường di chuyển 78 km",
      "Tốc độ tối đa 78 km/1 lần sạc Quãng đường di chuyển 1",
    ],
    slogan:
      "Evo Lite Neo - Xe máy điện cho học sinh (không yêu cầu bằng lái). Hệ thống phanh an toàn, vận hành êm ái, thiết kế trẻ trung và cốp 17L tiện dụng. Xem ngay chính sách và ưu đãi mới nhất!",
    variants: [
      {
        id: "evo-lite-neo",
        name: "EVO Lite Neo",
        price: 14400000,
      },
    ],
    overview: {
      title: "Evo Lite Neo - Xe máy điện cho học sinh (không yêu cầu bằng lái)",
      subtitle:
        "Evo Lite Neo - Xe máy điện cho học sinh (không yêu cầu bằng lái). Hệ thống phanh an toàn, vận hành êm ái, thiết kế trẻ trung và cốp 17L tiện dụng. Xem ngay chính sách và ưu đãi mới nhất!",
      bullets: [
        "Quãng đường di chuyển 78 km",
        "Tốc độ tối đa 78 km/1 lần sạc Quãng đường di chuyển 1",
        "49 km/h",
      ],
      image: "/images/vinfast/scooters/evo-lite-neo.webp",
    },
    exterior: [
      {
        title: "VẬN HÀNH ÊM ÁI ĐI MUÔN NƠI",
        desc: "Thân xe được thiết kế công thái học tối ưu, tạo cảm giác thoải mái cho người lái và người ngồi sau, giúp người lái xe có thể chạy xe trong thời gian dài.",
        image: "/images/vinfast/scooters/evo-lite-neo.webp",
      },
      {
        title: "THIẾT KẾ THÂN THIỆN VỚI NGƯỜI DÙNG",
        desc: "Kích thước tầm trung phù hợp với người Việt tạo cảm giác lái thoải mái, êm ái trên nhiều loại địa hình.",
        image: "/images/vinfast/scooters/evo-lite-neo.webp",
      },
    ],
    specGroups: [
      {
        category: "Thông số kỹ thuật (VinFast)",
        items: [
          {
            label: "Quãng đường di chuyển/tháng",
            value: "nhỏ hơn hoặc bằng 500 km",
          },
          {
            label: "Quãng đường di chuyển/tháng",
            value: "từ trên 500 km tới 1.000 km",
          },
          {
            label: "Quãng đường di chuyển/tháng",
            value: "từ trên 1.000 km tới dưới 2.000 km",
          },
          {
            label: "Quãng đường di chuyển/tháng",
            value: "từ 2.000 km",
          },
        ],
      },
    ],
    quickSpecs: {
      range: 500,
      topSpeed: 0,
      motorPower: 0,
      trunk: 0,
      chargingTime: "—",
      weight: 105,
    },
  },
};
